/**
 * Demo businesses.
 *
 * Every row is inserted with is_demo = true and surfaces a visible "Demo listing"
 * badge. Names are deliberately generic-descriptive rather than plausible
 * trading names, so no real Tanzanian operator can be mistaken for one of these,
 * and none of them is marked verified in a way that implies a real credential.
 *
 * Replace wholesale via the admin panel before launch.
 */

const D = (en, de, fr, it) => ({ en, de, fr, it });

export const businesses = [
  {
    slug: 'demo-serengeti-plains-safaris',
    name: 'Demo — Serengeti Plains Safaris',
    category: 'safaris',
    destinations: ['serengeti', 'ngorongoro', 'arusha'],
    city: 'Arusha',
    tier: 'featured',
    verified: true,
    rating: 4.8,
    email: 'hello@example-serengeti-plains.test',
    phone: '+255 700 000 001',
    whatsapp: '+255700000001',
    website: 'https://example-serengeti-plains.test',
    foundedYear: 2011,
    teamSize: 24,
    tagline: D(
      'Migration-timed safaris across the northern circuit',
      'Safaris im Rhythmus der Tierwanderung',
      'Des safaris calés sur la Grande Migration',
      'Safari sincronizzati con la Grande Migrazione',
    ),
    shortDescription: D(
      'Small-group and private safaris built around where the herds actually are that month.',
      'Kleingruppen- und Privatsafaris, ausgerichtet auf den tatsächlichen Standort der Herden.',
      'Safaris privés et en petits groupes calés sur la position réelle des troupeaux.',
      'Safari privati e in piccoli gruppi basati sulla posizione reale delle mandrie.',
    ),
    description: D(
      'A demonstration listing showing how a safari operator profile appears. Fleet of extended-range Land Cruisers, guides certified to Tanzania Professional Safari Guide standard, and camps positioned by season rather than by contract.',
      'Ein Beispieleintrag, der zeigt, wie das Profil eines Safari-Veranstalters aussieht. Land Cruiser mit erweiterter Reichweite, nach tansanischem Standard zertifizierte Guides und Camps, die nach Saison statt nach Vertrag gewählt werden.',
      'Une fiche de démonstration illustrant le profil d’un opérateur de safari. Flotte de Land Cruiser à grande autonomie, guides certifiés au standard tanzanien et camps choisis selon la saison plutôt que par contrat.',
      'Una scheda dimostrativa che mostra il profilo di un operatore safari. Flotta di Land Cruiser a lunga autonomia, guide certificate secondo lo standard tanzaniano e campi scelti in base alla stagione.',
    ),
  },
  {
    slug: 'demo-crater-highlands-expeditions',
    name: 'Demo — Crater Highlands Expeditions',
    category: 'safaris',
    destinations: ['ngorongoro', 'serengeti'],
    city: 'Karatu',
    tier: 'premium',
    verified: true,
    rating: 4.6,
    email: 'hello@example-crater-highlands.test',
    phone: '+255 700 000 002',
    whatsapp: '+255700000002',
    foundedYear: 2015,
    teamSize: 12,
    tagline: D(
      'Crater descents and Maasai highland walks',
      'Kraterabfahrten und Wanderungen im Massai-Hochland',
      'Descentes dans le cratère et marches en pays massaï',
      'Discese nel cratere e camminate negli altopiani Maasai',
    ),
    shortDescription: D(
      'Dawn crater descents paired with walking routes through the highland communities above it.',
      'Kraterabfahrten im Morgengrauen, kombiniert mit Wanderungen durch die Hochlandgemeinden.',
      'Descentes à l’aube associées à des randonnées dans les communautés des hauts plateaux.',
      'Discese all’alba abbinate a percorsi a piedi tra le comunità degli altopiani.',
    ),
    description: D(
      'Demonstration listing. Specialises in the conservation area rather than the wider circuit, with early crater access and guided walks on the rim.',
      'Beispieleintrag. Spezialisiert auf das Schutzgebiet statt den gesamten Circuit, mit frühem Kraterzugang und geführten Wanderungen am Kraterrand.',
      'Fiche de démonstration. Spécialiste de l’aire de conservation plutôt que du circuit complet, avec accès matinal au cratère et marches guidées sur le rebord.',
      'Scheda dimostrativa. Specializzata nell’area di conservazione più che nel circuito completo, con accesso mattutino al cratere e camminate guidate sull’orlo.',
    ),
  },
  {
    slug: 'demo-southern-rivers-safari-co',
    name: 'Demo — Southern Rivers Safari Co.',
    category: 'safaris',
    destinations: ['nyerere', 'dar-es-salaam'],
    city: 'Dar es Salaam',
    tier: 'premium',
    verified: false,
    rating: 4.4,
    email: 'hello@example-southern-rivers.test',
    phone: '+255 700 000 003',
    whatsapp: '+255700000003',
    foundedYear: 2018,
    teamSize: 9,
    tagline: D(
      'Boat safaris on the Rufiji',
      'Bootssafaris auf dem Rufiji',
      'Safaris en bateau sur le Rufiji',
      'Safari in barca sul Rufiji',
    ),
    shortDescription: D(
      'Southern circuit specialists running boat and walking safaris in Nyerere National Park.',
      'Spezialisten für den Süden mit Boots- und Wandersafaris im Nyerere-Nationalpark.',
      'Spécialistes du circuit sud, safaris en bateau et à pied dans le parc de Nyerere.',
      'Specialisti del circuito sud, safari in barca e a piedi nel parco di Nyerere.',
    ),
    description: D(
      'Demonstration listing showing a southern-circuit operator. Fly-in packages from Dar es Salaam, river camps and walking safaris.',
      'Beispieleintrag für einen Veranstalter im Süden. Fly-in-Pakete ab Daressalam, Flusscamps und Wandersafaris.',
      'Fiche de démonstration d’un opérateur du sud. Forfaits fly-in depuis Dar es Salaam, camps fluviaux et safaris à pied.',
      'Scheda dimostrativa di un operatore del sud. Pacchetti fly-in da Dar es Salaam, campi fluviali e safari a piedi.',
    ),
  },
  {
    slug: 'demo-kilimanjaro-summit-guides',
    name: 'Demo — Kilimanjaro Summit Guides',
    category: 'activities',
    destinations: ['kilimanjaro', 'arusha'],
    city: 'Moshi',
    tier: 'featured',
    verified: true,
    rating: 4.9,
    email: 'hello@example-kili-summit.test',
    phone: '+255 700 000 004',
    whatsapp: '+255700000004',
    foundedYear: 2009,
    teamSize: 60,
    tagline: D(
      'Eight-day routes, fair porter wages, high summit rates',
      'Achttagesrouten, faire Trägerlöhne, hohe Gipfelquote',
      'Voies en huit jours, salaires équitables, taux de réussite élevé',
      'Itinerari di otto giorni, salari equi, alto tasso di vetta',
    ),
    shortDescription: D(
      'Lemosho and Machame routes with the extra acclimatisation day built in as standard.',
      'Lemosho- und Machame-Routen, zusätzlicher Akklimatisierungstag standardmäßig enthalten.',
      'Voies Lemosho et Machame avec journée d’acclimatation supplémentaire incluse.',
      'Vie Lemosho e Machame con giorno di acclimatamento extra incluso.',
    ),
    description: D(
      'Demonstration listing. Illustrates how a trekking operator presents route options, success rates and porter welfare commitments.',
      'Beispieleintrag. Zeigt, wie ein Trekking-Veranstalter Routenoptionen, Erfolgsquoten und Verpflichtungen zum Trägerwohl darstellt.',
      'Fiche de démonstration. Illustre la présentation des voies, des taux de réussite et des engagements envers les porteurs.',
      'Scheda dimostrativa. Mostra come un operatore di trekking presenta vie, tassi di successo e impegni verso i portatori.',
    ),
  },
  {
    slug: 'demo-stone-town-heritage-hotel',
    name: 'Demo — Stone Town Heritage Hotel',
    category: 'hotels',
    destinations: ['zanzibar'],
    city: 'Zanzibar City',
    tier: 'premium',
    verified: true,
    rating: 4.5,
    email: 'hello@example-stonetown-heritage.test',
    phone: '+255 700 000 005',
    whatsapp: '+255700000005',
    foundedYear: 2014,
    teamSize: 30,
    tagline: D(
      'A restored merchant house in the old quarter',
      'Ein restauriertes Kaufmannshaus in der Altstadt',
      'Une maison de marchand restaurée dans la vieille ville',
      'Una casa mercantile restaurata nel centro storico',
    ),
    shortDescription: D(
      'Fourteen rooms around a coral-stone courtyard, two minutes from the seafront.',
      'Vierzehn Zimmer um einen Innenhof aus Korallenstein, zwei Minuten vom Meer.',
      'Quatorze chambres autour d’une cour en pierre de corail, à deux minutes du front de mer.',
      'Quattordici camere attorno a un cortile in pietra corallina, a due minuti dal lungomare.',
    ),
    description: D(
      'Demonstration listing showing a boutique hotel profile: rooms, location, amenities and a rooftop restaurant.',
      'Beispieleintrag für ein Boutique-Hotel: Zimmer, Lage, Ausstattung und Dachterrassenrestaurant.',
      'Fiche de démonstration d’un hôtel de charme : chambres, emplacement, équipements et restaurant en terrasse.',
      'Scheda dimostrativa di un boutique hotel: camere, posizione, servizi e ristorante sul tetto.',
    ),
  },
  {
    slug: 'demo-nungwi-beach-resort',
    name: 'Demo — Nungwi Beach Resort',
    category: 'hotels',
    destinations: ['zanzibar'],
    city: 'Nungwi',
    tier: 'premium',
    verified: false,
    rating: 4.3,
    email: 'hello@example-nungwi-beach.test',
    phone: '+255 700 000 006',
    whatsapp: '+255700000006',
    foundedYear: 2016,
    teamSize: 45,
    tagline: D(
      'North coast, swimmable at any tide',
      'Nordküste, bei jeder Tide schwimmbar',
      'Côte nord, baignade à toute marée',
      'Costa nord, balneabile con ogni marea',
    ),
    shortDescription: D(
      'Beachfront rooms on the tip of the island, where the tide never strands the swimming.',
      'Strandzimmer an der Inselspitze, wo die Gezeiten das Schwimmen nie verhindern.',
      'Chambres en bord de plage à la pointe de l’île, où la marée n’empêche jamais la baignade.',
      'Camere fronte spiaggia sulla punta dell’isola, dove la marea non impedisce mai il bagno.',
    ),
    description: D(
      'Demonstration listing for a beach resort, showing room types, dive centre and airport transfer options.',
      'Beispieleintrag für ein Strandresort mit Zimmerkategorien, Tauchbasis und Flughafentransfers.',
      'Fiche de démonstration d’un resort balnéaire : types de chambres, centre de plongée et transferts.',
      'Scheda dimostrativa di un resort balneare: tipologie di camere, centro immersioni e transfer.',
    ),
  },
  {
    slug: 'demo-serengeti-tented-camp',
    name: 'Demo — Serengeti Tented Camp',
    category: 'hotels',
    destinations: ['serengeti'],
    city: 'Seronera',
    tier: 'featured',
    verified: true,
    rating: 4.7,
    email: 'hello@example-serengeti-camp.test',
    phone: '+255 700 000 007',
    whatsapp: '+255700000007',
    foundedYear: 2012,
    teamSize: 28,
    tagline: D(
      'A mobile camp that moves with the herds',
      'Ein mobiles Camp, das mit den Herden zieht',
      'Un camp mobile qui suit les troupeaux',
      'Un campo mobile che segue le mandrie',
    ),
    shortDescription: D(
      'Twelve tents relocated three times a year to stay within reach of the migration.',
      'Zwölf Zelte, dreimal jährlich verlegt, um nah an der Tierwanderung zu bleiben.',
      'Douze tentes déplacées trois fois par an pour rester près de la migration.',
      'Dodici tende spostate tre volte l’anno per restare vicino alla migrazione.',
    ),
    description: D(
      'Demonstration listing for a seasonal tented camp, showing how mobile camps describe their positions through the year.',
      'Beispieleintrag für ein saisonales Zeltcamp und wie mobile Camps ihre Standorte im Jahresverlauf beschreiben.',
      'Fiche de démonstration d’un camp de toile saisonnier et de la façon dont les camps mobiles décrivent leurs emplacements.',
      'Scheda dimostrativa di un campo tendato stagionale e di come i campi mobili descrivono le loro posizioni.',
    ),
  },
  {
    slug: 'demo-arusha-coffee-lodge',
    name: 'Demo — Arusha Coffee Lodge',
    category: 'hotels',
    destinations: ['arusha'],
    city: 'Arusha',
    tier: 'free',
    verified: false,
    rating: 4.2,
    email: 'hello@example-arusha-coffee.test',
    phone: '+255 700 000 008',
    foundedYear: 2019,
    teamSize: 18,
    tagline: D(
      'First and last night, on a working coffee farm',
      'Erste und letzte Nacht auf einer Kaffeefarm',
      'Première et dernière nuit dans une ferme de café',
      'Prima e ultima notte in una piantagione di caffè',
    ),
    shortDescription: D(
      'Garden rooms twenty minutes from the airport, built for the night either side of a safari.',
      'Gartenzimmer zwanzig Minuten vom Flughafen, ideal für die Nacht vor und nach der Safari.',
      'Chambres sur jardin à vingt minutes de l’aéroport, pour la nuit avant et après le safari.',
      'Camere sul giardino a venti minuti dall’aeroporto, per la notte prima e dopo il safari.',
    ),
    description: D(
      'Demonstration listing showing a free-tier profile with limited media and no featured placement.',
      'Beispieleintrag für ein Free-Tier-Profil mit begrenzten Medien und ohne Empfehlungsplatzierung.',
      'Fiche de démonstration d’un profil gratuit, médias limités et sans mise en avant.',
      'Scheda dimostrativa di un profilo gratuito, contenuti limitati e senza posizionamento in evidenza.',
    ),
  },
  {
    slug: 'demo-zanzibar-dive-centre',
    name: 'Demo — Zanzibar Dive Centre',
    category: 'activities',
    destinations: ['zanzibar'],
    city: 'Nungwi',
    tier: 'premium',
    verified: true,
    rating: 4.6,
    email: 'hello@example-zanzibar-dive.test',
    phone: '+255 700 000 009',
    whatsapp: '+255700000009',
    foundedYear: 2013,
    teamSize: 14,
    tagline: D(
      'Mnemba atoll dives and PADI courses',
      'Tauchgänge am Mnemba-Atoll und PADI-Kurse',
      'Plongées à l’atoll de Mnemba et cours PADI',
      'Immersioni all’atollo di Mnemba e corsi PADI',
    ),
    shortDescription: D(
      'Daily boats to Mnemba, open water through divemaster, and snorkelling for non-divers.',
      'Tägliche Bootsfahrten nach Mnemba, Open Water bis Divemaster, Schnorcheln für Nichttaucher.',
      'Sorties quotidiennes à Mnemba, de l’open water au divemaster, snorkeling pour les non-plongeurs.',
      'Uscite giornaliere a Mnemba, dall’open water al divemaster, snorkeling per non subacquei.',
    ),
    description: D(
      'Demonstration listing for a dive operator, showing course levels, site list and equipment hire.',
      'Beispieleintrag für eine Tauchbasis mit Kursstufen, Tauchplätzen und Ausrüstungsverleih.',
      'Fiche de démonstration d’un centre de plongée : niveaux de cours, sites et location de matériel.',
      'Scheda dimostrativa di un centro immersioni: livelli dei corsi, siti e noleggio attrezzatura.',
    ),
  },
  {
    slug: 'demo-usambara-hiking-collective',
    name: 'Demo — Usambara Hiking Collective',
    category: 'activities',
    destinations: ['tanga'],
    city: 'Lushoto',
    tier: 'free',
    verified: false,
    rating: 4.4,
    email: 'hello@example-usambara-hiking.test',
    phone: '+255 700 000 010',
    whatsapp: '+255700000010',
    foundedYear: 2020,
    teamSize: 6,
    tagline: D(
      'Village-to-village walks in the Usambaras',
      'Wanderungen von Dorf zu Dorf in den Usambara-Bergen',
      'Randonnées de village en village dans les Usambara',
      'Camminate di villaggio in villaggio negli Usambara',
    ),
    shortDescription: D(
      'Guided multi-day hikes staying in village guesthouses, run as a local cooperative.',
      'Geführte Mehrtageswanderungen mit Übernachtung in Dorfgasthäusern, als lokale Kooperative geführt.',
      'Randonnées guidées de plusieurs jours avec nuitées chez l’habitant, gérées en coopérative locale.',
      'Escursioni guidate di più giorni con pernottamento nei villaggi, gestite come cooperativa locale.',
    ),
    description: D(
      'Demonstration listing showing a small community-run activity provider.',
      'Beispieleintrag für einen kleinen, gemeinschaftlich geführten Anbieter.',
      'Fiche de démonstration d’un petit prestataire communautaire.',
      'Scheda dimostrativa di un piccolo operatore gestito dalla comunità.',
    ),
  },
  {
    slug: 'demo-northern-circuit-4x4-hire',
    name: 'Demo — Northern Circuit 4x4 Hire',
    category: 'car-rental',
    destinations: ['arusha', 'serengeti', 'ngorongoro', 'kilimanjaro'],
    city: 'Arusha',
    tier: 'premium',
    verified: true,
    rating: 4.5,
    email: 'hello@example-northern-4x4.test',
    phone: '+255 700 000 011',
    whatsapp: '+255700000011',
    foundedYear: 2017,
    teamSize: 20,
    tagline: D(
      'Self-drive and chauffeured Land Cruisers',
      'Land Cruiser als Selbstfahrer oder mit Fahrer',
      'Land Cruiser en autotour ou avec chauffeur',
      'Land Cruiser con o senza autista',
    ),
    shortDescription: D(
      'Rooftop-tent equipped 4x4s with recovery kit, or a vehicle with a guide-driver.',
      'Allradfahrzeuge mit Dachzelt und Bergeausrüstung, oder Fahrzeug mit Guide-Fahrer.',
      '4x4 équipés de tentes de toit et kit de désensablage, ou véhicule avec chauffeur-guide.',
      '4x4 con tenda da tetto e kit di recupero, oppure veicolo con autista-guida.',
    ),
    description: D(
      'Demonstration listing for a vehicle hire company, showing fleet, insurance terms and delivery points.',
      'Beispieleintrag für einen Autovermieter mit Fuhrpark, Versicherungsbedingungen und Übergabeorten.',
      'Fiche de démonstration d’un loueur : flotte, conditions d’assurance et points de livraison.',
      'Scheda dimostrativa di un autonoleggio: flotta, condizioni assicurative e punti di consegna.',
    ),
  },
  {
    slug: 'demo-coastal-transfers-tanzania',
    name: 'Demo — Coastal Transfers Tanzania',
    category: 'car-rental',
    destinations: ['dar-es-salaam', 'zanzibar', 'tanga'],
    city: 'Dar es Salaam',
    tier: 'free',
    verified: false,
    rating: 4.1,
    email: 'hello@example-coastal-transfers.test',
    phone: '+255 700 000 012',
    whatsapp: '+255700000012',
    foundedYear: 2021,
    teamSize: 8,
    tagline: D(
      'Airport, port and intercity transfers',
      'Transfers zu Flughafen, Hafen und zwischen Städten',
      'Transferts aéroport, port et interurbains',
      'Transfer aeroporto, porto e intercity',
    ),
    shortDescription: D(
      'Fixed-price runs between airports, ferry terminals and coastal hotels.',
      'Festpreisfahrten zwischen Flughäfen, Fähranlegern und Küstenhotels.',
      'Trajets à prix fixe entre aéroports, terminaux de ferry et hôtels côtiers.',
      'Tratte a prezzo fisso tra aeroporti, terminal dei traghetti e hotel costieri.',
    ),
    description: D(
      'Demonstration listing for a transfer service, showing route pricing and vehicle classes.',
      'Beispieleintrag für einen Transferdienst mit Streckenpreisen und Fahrzeugklassen.',
      'Fiche de démonstration d’un service de transfert : tarifs par trajet et catégories de véhicules.',
      'Scheda dimostrativa di un servizio transfer: prezzi per tratta e classi di veicoli.',
    ),
  },
  {
    slug: 'demo-serengeti-birding-guide',
    name: 'Demo — Serengeti Birding Guide',
    category: 'tour-guides',
    destinations: ['serengeti', 'arusha'],
    city: 'Arusha',
    tier: 'free',
    verified: true,
    rating: 4.9,
    email: 'hello@example-birding-guide.test',
    phone: '+255 700 000 013',
    whatsapp: '+255700000013',
    foundedYear: 2010,
    teamSize: 1,
    tagline: D(
      'Independent guide — birds and big cats',
      'Unabhängiger Guide — Vögel und Großkatzen',
      'Guide indépendant — oiseaux et grands félins',
      'Guida indipendente — uccelli e grandi felini',
    ),
    shortDescription: D(
      'Licensed independent guide working in English and German, specialising in birding.',
      'Lizenzierter unabhängiger Guide für Englisch und Deutsch, spezialisiert auf Vogelbeobachtung.',
      'Guide indépendant agréé, anglais et allemand, spécialisé en ornithologie.',
      'Guida indipendente autorizzata, inglese e tedesco, specializzata in birdwatching.',
    ),
    description: D(
      'Demonstration listing showing an individual guide profile — languages, specialities and day rate.',
      'Beispieleintrag für ein Guide-Profil — Sprachen, Fachgebiete und Tagessatz.',
      'Fiche de démonstration d’un guide individuel — langues, spécialités et tarif journalier.',
      'Scheda dimostrativa di una guida individuale — lingue, specialità e tariffa giornaliera.',
    ),
  },
  {
    slug: 'demo-stone-town-walking-guides',
    name: 'Demo — Stone Town Walking Guides',
    category: 'tour-guides',
    destinations: ['zanzibar'],
    city: 'Zanzibar City',
    tier: 'free',
    verified: false,
    rating: 4.3,
    email: 'hello@example-stonetown-walks.test',
    phone: '+255 700 000 014',
    whatsapp: '+255700000014',
    foundedYear: 2018,
    teamSize: 4,
    tagline: D(
      'History walks through the old quarter',
      'Historische Rundgänge durch die Altstadt',
      'Balades historiques dans la vieille ville',
      'Passeggiate storiche nel centro storico',
    ),
    shortDescription: D(
      'Two-hour walks covering the Swahili, Omani and colonial layers of Stone Town.',
      'Zweistündige Rundgänge zu den Suaheli-, omanischen und kolonialen Schichten Stone Towns.',
      'Balades de deux heures couvrant les strates swahilie, omanaise et coloniale de Stone Town.',
      'Passeggiate di due ore tra gli strati swahili, omaniti e coloniali di Stone Town.',
    ),
    description: D(
      'Demonstration listing for a small guiding outfit offering scheduled and private walks.',
      'Beispieleintrag für einen kleinen Guide-Betrieb mit festen und privaten Rundgängen.',
      'Fiche de démonstration d’une petite structure de guidage, visites régulières et privées.',
      'Scheda dimostrativa di una piccola realtà di guide, visite programmate e private.',
    ),
  },
  {
    slug: 'demo-forodhani-seafood-kitchen',
    name: 'Demo — Forodhani Seafood Kitchen',
    category: 'restaurants',
    destinations: ['zanzibar'],
    city: 'Zanzibar City',
    tier: 'free',
    verified: false,
    rating: 4.4,
    email: 'hello@example-forodhani-kitchen.test',
    phone: '+255 700 000 015',
    whatsapp: '+255700000015',
    foundedYear: 2017,
    teamSize: 11,
    tagline: D(
      'Swahili seafood by the harbour',
      'Suaheli-Fischküche am Hafen',
      'Cuisine swahilie de la mer, sur le port',
      'Cucina swahili di mare, sul porto',
    ),
    shortDescription: D(
      'Grilled catch, coconut curries and a cooking class three afternoons a week.',
      'Gegrillter Fang, Kokos-Currys und dreimal wöchentlich ein Kochkurs.',
      'Poisson grillé, curry au lait de coco et cours de cuisine trois après-midis par semaine.',
      'Pescato alla griglia, curry al cocco e un corso di cucina tre pomeriggi a settimana.',
    ),
    description: D(
      'Demonstration listing for a restaurant, showing menu highlights, opening hours and the cooking class as a bookable experience.',
      'Beispieleintrag für ein Restaurant mit Menü-Highlights, Öffnungszeiten und buchbarem Kochkurs.',
      'Fiche de démonstration d’un restaurant : plats phares, horaires et cours de cuisine réservable.',
      'Scheda dimostrativa di un ristorante: piatti principali, orari e corso di cucina prenotabile.',
    ),
  },
  {
    slug: 'demo-arusha-street-food-tours',
    name: 'Demo — Arusha Street Food Tours',
    category: 'restaurants',
    destinations: ['arusha'],
    city: 'Arusha',
    tier: 'free',
    verified: false,
    rating: 4.5,
    email: 'hello@example-arusha-streetfood.test',
    phone: '+255 700 000 016',
    whatsapp: '+255700000016',
    foundedYear: 2022,
    teamSize: 3,
    tagline: D(
      'Evening food walks through the market',
      'Abendliche Food-Touren über den Markt',
      'Balades gourmandes du soir au marché',
      'Passeggiate gastronomiche serali al mercato',
    ),
    shortDescription: D(
      'Six stops, mishkaki to chipsi mayai, with a guide who explains what you are eating.',
      'Sechs Stationen, von Mishkaki bis Chipsi Mayai, mit erklärendem Guide.',
      'Six étapes, du mishkaki au chipsi mayai, avec un guide qui explique chaque plat.',
      'Sei tappe, dal mishkaki al chipsi mayai, con una guida che spiega ogni piatto.',
    ),
    description: D(
      'Demonstration listing for a food tour operator, showing itinerary, dietary options and group size.',
      'Beispieleintrag für einen Food-Tour-Anbieter mit Ablauf, Ernährungsoptionen und Gruppengröße.',
      'Fiche de démonstration d’un opérateur de tours culinaires : itinéraire, régimes et taille du groupe.',
      'Scheda dimostrativa di un operatore di food tour: itinerario, opzioni alimentari e dimensione del gruppo.',
    ),
  },
];
