/**
 * Demo travel guides.
 *
 * Topics are chosen for search demand rather than for variety — "how much does
 * a Tanzania safari cost" and "best time to visit the Serengeti" are among the
 * highest-volume planning queries in this niche, and guides are the only surface
 * on the site permitted to carry ads.
 *
 * Bodies are markdown and deliberately short: these are structural placeholders
 * for a real content programme, not the finished article.
 */

const t = (en, de, fr, it) => ({ en, de, fr, it });

export const guides = [
  {
    key: 'safari-cost',
    destination: null,
    category: 'safaris',
    readingMinutes: 6,
    featured: true,
    sortOrder: 1,
    title: t(
      'How much does a Tanzania safari actually cost?',
      'Was kostet eine Safari in Tansania wirklich?',
      'Combien coûte réellement un safari en Tanzanie ?',
      'Quanto costa davvero un safari in Tanzania?',
    ),
    slug: t('tanzania-safari-cost', 'tansania-safari-kosten', 'cout-safari-tanzanie', 'costo-safari-tanzania'),
    excerpt: t(
      'Park fees, vehicles and camps broken down, and why the cheapest quote is rarely the cheapest trip.',
      'Parkgebühren, Fahrzeuge und Camps aufgeschlüsselt — und warum das günstigste Angebot selten die günstigste Reise ist.',
      'Droits de parc, véhicules et camps détaillés, et pourquoi le devis le moins cher est rarement le voyage le moins cher.',
      'Tariffe dei parchi, veicoli e campi nel dettaglio, e perché il preventivo più basso raramente è il viaggio più economico.',
    ),
    body: t(
      `## The fixed costs nobody can discount\n\nPark fees are set by the government and identical for every operator. Serengeti entry is around US$70 per person per day, the Ngorongoro Crater adds roughly US$70 plus a US$295 vehicle fee for the descent. On a seven-day northern circuit, fees alone are typically US$700–900 per person before anyone has driven anywhere.\n\nThis matters because it puts a hard floor under pricing. An operator quoting far below the market is not being efficient — they are cutting something, and it is usually the vehicle, the guide, or the camp.\n\n## What actually varies\n\n- **Accommodation** — from US$60 a night in a public campsite to over US$1,500 in a luxury camp. This is the single biggest lever.\n- **Vehicle and guide** — a private Land Cruiser with an experienced guide costs meaningfully more than a shared seat, and is the difference most people notice.\n- **Group size** — costs per person fall sharply from two to four travelers.\n\n## Rough guide\n\n| Style | Per person per day |\n|---|---|\n| Camping, shared vehicle | US$180–280 |\n| Mid-range lodge | US$350–550 |\n| Luxury camp, private vehicle | US$700–1,500+ |\n\n## Before you book\n\nAsk what is *not* included. Park fees, flights, tips and drinks are the four things most often left out of a headline price.`,
      `## Die Fixkosten, die niemand rabattieren kann\n\nParkgebühren werden staatlich festgelegt und sind für jeden Veranstalter gleich. Der Serengeti-Eintritt liegt bei etwa 70 US$ pro Person und Tag, der Ngorongoro-Krater kommt mit rund 70 US$ plus 295 US$ Fahrzeuggebühr für die Abfahrt hinzu. Auf einer siebentägigen Nordroute betragen allein die Gebühren meist 700–900 US$ pro Person.\n\nDas setzt eine harte Preisuntergrenze. Wer deutlich darunter anbietet, arbeitet nicht effizienter — er spart etwas ein, meist am Fahrzeug, am Guide oder am Camp.\n\n## Was tatsächlich variiert\n\n- **Unterkunft** — von 60 US$ pro Nacht auf einem öffentlichen Campingplatz bis über 1.500 US$ im Luxuscamp. Der größte Hebel.\n- **Fahrzeug und Guide** — ein privater Land Cruiser mit erfahrenem Guide kostet deutlich mehr als ein geteilter Sitzplatz.\n- **Gruppengröße** — die Kosten pro Person sinken von zwei auf vier Reisende stark.\n\n## Richtwerte\n\n| Reisestil | Pro Person und Tag |\n|---|---|\n| Camping, geteiltes Fahrzeug | 180–280 US$ |\n| Mittelklasse-Lodge | 350–550 US$ |\n| Luxuscamp, privates Fahrzeug | 700–1.500+ US$ |\n\n## Vor der Buchung\n\nFragen Sie, was *nicht* enthalten ist. Parkgebühren, Flüge, Trinkgelder und Getränke fehlen am häufigsten im Angebotspreis.`,
      `## Les coûts fixes que personne ne peut réduire\n\nLes droits de parc sont fixés par l’État et identiques pour tous les opérateurs. L’entrée au Serengeti coûte environ 70 US$ par personne et par jour ; le cratère du Ngorongoro ajoute environ 70 US$ plus 295 US$ de droit de véhicule pour la descente. Sur un circuit nord de sept jours, les seuls droits représentent généralement 700 à 900 US$ par personne.\n\nCela impose un plancher tarifaire. Un opérateur qui propose bien moins n’est pas plus efficace : il rogne quelque part, souvent sur le véhicule, le guide ou le camp.\n\n## Ce qui varie réellement\n\n- **L’hébergement** — de 60 US$ la nuit en camping public à plus de 1 500 US$ en camp de luxe. Le principal levier.\n- **Véhicule et guide** — un Land Cruiser privé avec guide expérimenté coûte nettement plus qu’une place partagée.\n- **Taille du groupe** — le coût par personne chute fortement de deux à quatre voyageurs.\n\n## Ordres de grandeur\n\n| Style | Par personne et par jour |\n|---|---|\n| Camping, véhicule partagé | 180–280 US$ |\n| Lodge de milieu de gamme | 350–550 US$ |\n| Camp de luxe, véhicule privé | 700–1 500+ US$ |\n\n## Avant de réserver\n\nDemandez ce qui n’est **pas** inclus. Droits de parc, vols, pourboires et boissons sont les quatre oublis les plus fréquents.`,
      `## I costi fissi che nessuno può scontare\n\nLe tariffe dei parchi sono stabilite dallo Stato e identiche per ogni operatore. L’ingresso al Serengeti costa circa 70 US$ a persona al giorno; il cratere di Ngorongoro aggiunge circa 70 US$ più 295 US$ di tariffa veicolo per la discesa. Su un circuito nord di sette giorni, le sole tariffe ammontano di solito a 700–900 US$ a persona.\n\nQuesto fissa un limite minimo ai prezzi. Un operatore che propone molto meno non è più efficiente: sta tagliando qualcosa, di solito il veicolo, la guida o il campo.\n\n## Cosa varia davvero\n\n- **L’alloggio** — da 60 US$ a notte in un campeggio pubblico a oltre 1.500 US$ in un campo di lusso. La leva principale.\n- **Veicolo e guida** — un Land Cruiser privato con guida esperta costa sensibilmente più di un posto condiviso.\n- **Dimensione del gruppo** — il costo per persona cala nettamente da due a quattro viaggiatori.\n\n## Valori indicativi\n\n| Stile | Per persona al giorno |\n|---|---|\n| Campeggio, veicolo condiviso | 180–280 US$ |\n| Lodge di fascia media | 350–550 US$ |\n| Campo di lusso, veicolo privato | 700–1.500+ US$ |\n\n## Prima di prenotare\n\nChiedi cosa **non** è incluso. Tariffe dei parchi, voli, mance e bevande sono le quattro voci più spesso escluse.`,
    ),
  },
  {
    key: 'serengeti-when',
    destination: 'serengeti',
    category: 'safaris',
    readingMinutes: 5,
    featured: true,
    sortOrder: 2,
    title: t(
      'When to visit the Serengeti',
      'Wann ist die beste Reisezeit für die Serengeti?',
      'Quand visiter le Serengeti ?',
      'Quando visitare il Serengeti',
    ),
    slug: t('best-time-to-visit-serengeti', 'beste-reisezeit-serengeti', 'quand-visiter-serengeti', 'quando-visitare-serengeti'),
    excerpt: t(
      'The herds move all year. What changes is where they are — and that should decide your camp, not your dates.',
      'Die Herden ziehen das ganze Jahr. Es ändert sich nur, wo sie sind — und das sollte Ihr Camp bestimmen, nicht Ihr Reisedatum.',
      'Les troupeaux se déplacent toute l’année. Ce qui change, c’est leur position — et cela devrait déterminer votre camp, pas vos dates.',
      'Le mandrie si spostano tutto l’anno. Cambia solo dove si trovano — e questo dovrebbe determinare il campo, non le date.',
    ),
    body: t(
      `## There is no bad month\n\nThe Great Migration is a continuous loop, not an event. The wildebeest are always somewhere in the ecosystem; the question is which part.\n\n## The calendar\n\n- **January–March** — calving on the southern short-grass plains. Around 8,000 calves a day at the peak, which draws every predator in the region. The best months for cat sightings.\n- **April–May** — long rains. Fewest visitors, lowest prices, high grass and some camps closed.\n- **June** — the rut, herds concentrating in the Western Corridor. Grumeti crossings begin.\n- **July–September** — Mara River crossings in the north. The classic image, and the busiest and most expensive period.\n- **October–November** — the return south, short rains, green landscapes and far fewer vehicles.\n- **December** — herds back on the southern plains.\n\n## What this means for booking\n\nBook the camp that is near the herds in your month. A fixed lodge in the central Serengeti is convenient year-round but will not put you near a river crossing in August. Mobile camps move for exactly this reason.\n\nIf you only care about big cats rather than the crossings, February in the south is arguably better than August in the north — and materially cheaper.`,
      `## Es gibt keinen schlechten Monat\n\nDie Große Tierwanderung ist ein durchgehender Kreislauf, kein Einzelereignis. Die Gnus sind immer irgendwo im Ökosystem — die Frage ist nur, wo.\n\n## Der Kalender\n\n- **Januar–März** — Kalbungszeit in den südlichen Kurzgrasebenen. Auf dem Höhepunkt etwa 8.000 Kälber täglich, was alle Raubtiere anzieht. Die besten Monate für Großkatzen.\n- **April–Mai** — große Regenzeit. Wenigste Besucher, niedrigste Preise, hohes Gras, einige Camps geschlossen.\n- **Juni** — Brunftzeit, Herden im westlichen Korridor. Erste Grumeti-Durchquerungen.\n- **Juli–September** — Mara-Flussdurchquerungen im Norden. Das klassische Bild — und die teuerste, vollste Zeit.\n- **Oktober–November** — Rückzug nach Süden, kurze Regenzeit, grüne Landschaft, deutlich weniger Fahrzeuge.\n- **Dezember** — Herden zurück in den südlichen Ebenen.\n\n## Was das für die Buchung bedeutet\n\nBuchen Sie das Camp, das in Ihrem Monat nahe an den Herden liegt. Eine feste Lodge in der zentralen Serengeti ist ganzjährig praktisch, bringt Sie im August aber nicht an eine Flussdurchquerung. Genau dafür gibt es mobile Camps.\n\nWenn Sie Großkatzen wichtiger finden als Flussdurchquerungen, ist der Februar im Süden dem August im Norden vorzuziehen — und deutlich günstiger.`,
      `## Il n’y a pas de mauvais mois\n\nLa Grande Migration est une boucle continue, pas un événement. Les gnous sont toujours quelque part dans l’écosystème ; la question est de savoir où.\n\n## Le calendrier\n\n- **Janvier–mars** — mise bas dans les plaines herbeuses du sud. Jusqu’à 8 000 naissances par jour au pic, ce qui attire tous les prédateurs. Les meilleurs mois pour les félins.\n- **Avril–mai** — grandes pluies. Moins de visiteurs, prix les plus bas, herbe haute, certains camps fermés.\n- **Juin** — le rut, troupeaux concentrés dans le couloir ouest. Premières traversées du Grumeti.\n- **Juillet–septembre** — traversées de la Mara au nord. L’image classique, et la période la plus chère et la plus fréquentée.\n- **Octobre–novembre** — retour vers le sud, petites pluies, paysages verts et beaucoup moins de véhicules.\n- **Décembre** — troupeaux de retour dans les plaines du sud.\n\n## Ce que cela implique\n\nRéservez le camp proche des troupeaux pour votre mois. Un lodge fixe dans le Serengeti central est pratique toute l’année mais ne vous mettra pas près d’une traversée en août. Les camps mobiles existent précisément pour cela.\n\nSi vous tenez plus aux félins qu’aux traversées, février au sud vaut mieux qu’août au nord — et coûte nettement moins.`,
      `## Non esiste un mese sbagliato\n\nLa Grande Migrazione è un ciclo continuo, non un evento. Gli gnu sono sempre da qualche parte nell’ecosistema; la domanda è dove.\n\n## Il calendario\n\n- **Gennaio–marzo** — parti nelle pianure erbose meridionali. Fino a 8.000 nascite al giorno nel picco, cosa che attira tutti i predatori. I mesi migliori per i felini.\n- **Aprile–maggio** — grandi piogge. Meno visitatori, prezzi più bassi, erba alta e alcuni campi chiusi.\n- **Giugno** — stagione degli accoppiamenti, mandrie nel corridoio occidentale. Primi attraversamenti del Grumeti.\n- **Luglio–settembre** — attraversamenti del fiume Mara a nord. L’immagine classica, e il periodo più caro e affollato.\n- **Ottobre–novembre** — ritorno a sud, piogge brevi, paesaggi verdi e molti meno veicoli.\n- **Dicembre** — mandrie di nuovo nelle pianure meridionali.\n\n## Cosa significa per la prenotazione\n\nPrenota il campo vicino alle mandrie nel tuo mese. Un lodge fisso nel Serengeti centrale è comodo tutto l’anno ma ad agosto non ti porterà vicino a un attraversamento. I campi mobili esistono proprio per questo.\n\nSe ti interessano più i felini degli attraversamenti, febbraio a sud batte agosto a nord — e costa molto meno.`,
    ),
  },
  {
    key: 'kilimanjaro-routes',
    destination: 'kilimanjaro',
    category: 'activities',
    readingMinutes: 5,
    sortOrder: 3,
    title: t(
      'Which Kilimanjaro route should you choose?',
      'Welche Kilimandscharo-Route ist die richtige?',
      'Quelle voie choisir pour le Kilimandjaro ?',
      'Quale via scegliere per il Kilimangiaro?',
    ),
    slug: t('kilimanjaro-routes-compared', 'kilimandscharo-routen-vergleich', 'voies-kilimandjaro-comparees', 'vie-kilimangiaro-a-confronto'),
    excerpt: t(
      'Seven routes, very different success rates. The deciding factor is days, not difficulty.',
      'Sieben Routen mit sehr unterschiedlichen Erfolgsquoten. Entscheidend ist die Dauer, nicht die Schwierigkeit.',
      'Sept voies, des taux de réussite très différents. Le facteur décisif est le nombre de jours, pas la difficulté.',
      'Sette vie, tassi di successo molto diversi. Il fattore decisivo è il numero di giorni, non la difficoltà.',
    ),
    body: t(
      `## The number that matters\n\nSummit success on Kilimanjaro correlates far more strongly with the number of days on the mountain than with fitness, age or route difficulty. Five-day itineraries succeed roughly half the time. Eight-day itineraries exceed ninety percent.\n\nAltitude sickness is the reason people turn back, and the only reliable defence is time.\n\n## The routes\n\n- **Lemosho (7–8 days)** — the highest success rates. Long western approach, excellent acclimatisation profile, quieter in the early days.\n- **Machame (6–7 days)** — the popular choice. Steeper, busier, good climb-high-sleep-low profile.\n- **Rongai (6–7 days)** — the only northern approach. Drier, quieter, gentler, but a less varied landscape.\n- **Marangu (5–6 days)** — huts rather than tents. Often sold as the easy route; it has the poorest success rate because it is the shortest.\n- **Northern Circuit (9 days)** — the longest and highest-success route, and the quietest.\n\n## Practical advice\n\nPay for the extra day. It costs a few hundred dollars against a trip that already costs thousands, and it is the difference between standing on the summit and turning back at 4,600 metres.`,
      `## Die entscheidende Zahl\n\nDer Gipfelerfolg am Kilimandscharo hängt weit stärker von der Anzahl der Tage am Berg ab als von Fitness, Alter oder Schwierigkeitsgrad. Fünftagestouren gelingen etwa zur Hälfte, Achttagestouren zu über neunzig Prozent.\n\nHöhenkrankheit ist der Grund für Abbrüche — und Zeit die einzige verlässliche Gegenmaßnahme.\n\n## Die Routen\n\n- **Lemosho (7–8 Tage)** — höchste Erfolgsquote. Langer Anstieg von Westen, ausgezeichnetes Akklimatisierungsprofil, anfangs ruhiger.\n- **Machame (6–7 Tage)** — die beliebte Wahl. Steiler, voller, gutes Höhenprofil.\n- **Rongai (6–7 Tage)** — einziger Anstieg von Norden. Trockener, ruhiger, sanfter, landschaftlich weniger abwechslungsreich.\n- **Marangu (5–6 Tage)** — Hütten statt Zelte. Oft als leichte Route verkauft, hat aber die schlechteste Erfolgsquote, weil sie die kürzeste ist.\n- **Northern Circuit (9 Tage)** — längste Route, höchste Erfolgsquote, am ruhigsten.\n\n## Praktischer Rat\n\nZahlen Sie für den zusätzlichen Tag. Er kostet ein paar Hundert Dollar bei einer Reise, die ohnehin Tausende kostet — und entscheidet zwischen Gipfel und Umkehr auf 4.600 Metern.`,
      `## Le chiffre qui compte\n\nLa réussite au Kilimandjaro dépend bien plus du nombre de jours passés sur la montagne que de la condition physique, de l’âge ou de la difficulté. Les circuits de cinq jours réussissent environ une fois sur deux ; ceux de huit jours dépassent quatre-vingt-dix pour cent.\n\nLe mal aigu des montagnes est la cause des abandons, et le temps la seule parade fiable.\n\n## Les voies\n\n- **Lemosho (7–8 jours)** — les meilleurs taux de réussite. Longue approche par l’ouest, excellent profil d’acclimatation.\n- **Machame (6–7 jours)** — le choix populaire. Plus raide, plus fréquenté, bon profil.\n- **Rongai (6–7 jours)** — seule approche par le nord. Plus sèche, plus calme, plus douce, paysages moins variés.\n- **Marangu (5–6 jours)** — refuges plutôt que tentes. Vendue comme la voie facile, elle a le plus faible taux de réussite car la plus courte.\n- **Northern Circuit (9 jours)** — la plus longue, la plus sûre et la plus calme.\n\n## Conseil pratique\n\nPayez le jour supplémentaire. Quelques centaines de dollars sur un voyage qui en coûte des milliers, et c’est la différence entre le sommet et un demi-tour à 4 600 mètres.`,
      `## Il numero che conta\n\nIl successo in vetta al Kilimangiaro dipende molto più dal numero di giorni sulla montagna che dalla forma fisica, dall’età o dalla difficoltà. Gli itinerari di cinque giorni riescono circa una volta su due; quelli di otto superano il novanta per cento.\n\nIl mal di montagna è la ragione dei ritiri, e il tempo l’unica difesa affidabile.\n\n## Le vie\n\n- **Lemosho (7–8 giorni)** — i tassi di successo più alti. Lungo avvicinamento da ovest, ottimo profilo di acclimatamento.\n- **Machame (6–7 giorni)** — la scelta popolare. Più ripida, più affollata, buon profilo.\n- **Rongai (6–7 giorni)** — unico avvicinamento da nord. Più asciutta, tranquilla e dolce, paesaggi meno vari.\n- **Marangu (5–6 giorni)** — rifugi invece di tende. Venduta come la via facile, ha il tasso di successo peggiore perché è la più breve.\n- **Northern Circuit (9 giorni)** — la più lunga, con il successo più alto e la più tranquilla.\n\n## Consiglio pratico\n\nPaga il giorno in più. Costa qualche centinaio di dollari su un viaggio che ne costa migliaia, ed è la differenza tra la vetta e il dietrofront a 4.600 metri.`,
    ),
  },
  {
    key: 'safari-and-beach',
    destination: 'zanzibar',
    category: null,
    readingMinutes: 4,
    sortOrder: 4,
    title: t(
      'Combining a safari with Zanzibar',
      'Safari und Sansibar kombinieren',
      'Combiner un safari et Zanzibar',
      'Combinare safari e Zanzibar',
    ),
    slug: t('safari-and-zanzibar-itinerary', 'safari-und-sansibar-route', 'itineraire-safari-et-zanzibar', 'itinerario-safari-e-zanzibar'),
    excerpt: t(
      'How many days each deserves, and which order works better.',
      'Wie viele Tage jeder Teil verdient — und welche Reihenfolge besser funktioniert.',
      'Combien de jours accorder à chacun, et dans quel ordre.',
      'Quanti giorni dedicare a ciascuno e in che ordine.',
    ),
    body: t(
      `## The standard shape\n\nMost travelers combine six to eight days on the northern safari circuit with five to seven on Zanzibar. Under ten days total, do one or the other properly rather than both badly.\n\n## Safari first\n\nAlmost always the better order. Safari days start before dawn and involve long drives on rough roads; the beach is a much better recovery than a warm-up. Flying Arusha to Zanzibar takes about ninety minutes and avoids returning through Dar es Salaam.\n\n## How long on the island\n\nFive nights is comfortable: two in Stone Town, three on the coast. Seven if you want to dive or simply stop moving.\n\n## Which coast\n\n- **North (Nungwi, Kendwa)** — swimmable at any tide, busiest, most restaurants.\n- **East (Paje, Jambiani)** — dramatic tides, kitesurfing, quieter and cheaper.\n- **South-east (Michamvi)** — calmest, least developed.\n\nIf swimming on demand matters, choose the north. The east coast tide can retreat several hundred metres.`,
      `## Die übliche Aufteilung\n\nDie meisten kombinieren sechs bis acht Tage auf dem nördlichen Safari-Circuit mit fünf bis sieben auf Sansibar. Unter zehn Tagen insgesamt sollten Sie eines von beidem richtig machen statt beides schlecht.\n\n## Erst Safari\n\nFast immer die bessere Reihenfolge. Safaritage beginnen vor Sonnenaufgang und bedeuten lange Fahrten auf schlechten Pisten — der Strand eignet sich besser zur Erholung als zum Auftakt. Der Flug Arusha–Sansibar dauert etwa 90 Minuten und erspart den Umweg über Daressalam.\n\n## Wie lange auf der Insel\n\nFünf Nächte sind angenehm: zwei in Stone Town, drei an der Küste. Sieben, wenn Sie tauchen oder einfach ankommen wollen.\n\n## Welche Küste\n\n- **Norden (Nungwi, Kendwa)** — bei jeder Tide schwimmbar, am belebtesten.\n- **Osten (Paje, Jambiani)** — starke Gezeiten, Kitesurfen, ruhiger und günstiger.\n- **Südosten (Michamvi)** — am ruhigsten, am wenigsten erschlossen.\n\nWer jederzeit schwimmen möchte, wählt den Norden. An der Ostküste zieht sich das Wasser mehrere Hundert Meter zurück.`,
      `## La structure habituelle\n\nLa plupart des voyageurs associent six à huit jours de safari au nord et cinq à sept à Zanzibar. En dessous de dix jours au total, faites l’un ou l’autre correctement plutôt que les deux mal.\n\n## Le safari d’abord\n\nPresque toujours le bon ordre. Les journées de safari commencent avant l’aube et impliquent de longues pistes ; la plage se prête mieux à la récupération qu’à l’échauffement. Le vol Arusha–Zanzibar dure environ 90 minutes et évite de repasser par Dar es Salaam.\n\n## Combien de temps sur l’île\n\nCinq nuits sont confortables : deux à Stone Town, trois sur la côte. Sept si vous plongez ou souhaitez simplement vous poser.\n\n## Quelle côte\n\n- **Nord (Nungwi, Kendwa)** — baignable à toute marée, la plus animée.\n- **Est (Paje, Jambiani)** — marées marquées, kitesurf, plus calme et moins cher.\n- **Sud-est (Michamvi)** — la plus tranquille, la moins aménagée.\n\nSi nager à toute heure compte, choisissez le nord : à l’est, la mer peut se retirer de plusieurs centaines de mètres.`,
      `## La struttura tipica\n\nLa maggior parte dei viaggiatori combina sei-otto giorni di safari nel nord con cinque-sette a Zanzibar. Sotto i dieci giorni totali, meglio fare bene una cosa sola che entrambe male.\n\n## Prima il safari\n\nQuasi sempre l’ordine migliore. Le giornate di safari iniziano prima dell’alba e comportano lunghi trasferimenti su strade sconnesse; la spiaggia funziona meglio come recupero che come riscaldamento. Il volo Arusha–Zanzibar dura circa 90 minuti ed evita il rientro via Dar es Salaam.\n\n## Quanto restare sull’isola\n\nCinque notti sono comode: due a Stone Town, tre sulla costa. Sette se vuoi immergerti o semplicemente fermarti.\n\n## Quale costa\n\n- **Nord (Nungwi, Kendwa)** — balneabile con ogni marea, la più animata.\n- **Est (Paje, Jambiani)** — maree marcate, kitesurf, più tranquilla ed economica.\n- **Sud-est (Michamvi)** — la più quieta e meno sviluppata.\n\nSe conta poter nuotare sempre, scegli il nord: a est il mare può ritirarsi di centinaia di metri.`,
    ),
  },
  {
    key: 'packing',
    destination: null,
    category: 'safaris',
    readingMinutes: 4,
    sortOrder: 5,
    title: t(
      'What to pack for a Tanzania safari',
      'Packliste für eine Safari in Tansania',
      'Que mettre dans sa valise pour un safari en Tanzanie',
      'Cosa mettere in valigia per un safari in Tanzania',
    ),
    slug: t('tanzania-safari-packing-list', 'tansania-safari-packliste', 'liste-bagages-safari-tanzanie', 'cosa-portare-safari-tanzania'),
    excerpt: t(
      'Light aircraft weight limits, layers for cold mornings, and the things people consistently forget.',
      'Gewichtsgrenzen bei Kleinflugzeugen, Schichten für kalte Morgen und die häufigsten Vergesslichkeiten.',
      'Limites de poids en avion léger, couches pour les matins froids et les oublis les plus fréquents.',
      'Limiti di peso sugli aerei leggeri, strati per le mattine fredde e le dimenticanze più comuni.',
    ),
    body: t(
      `## The weight limit is real\n\nLight aircraft between camps typically allow 15 kg in a soft bag. Not 15 kg plus hand luggage, and not in a hard case. If your itinerary includes a flight, pack to that number from the start.\n\n## Layers, not warm clothes\n\nGame drives leave before sunrise when it can be close to freezing in an open vehicle at altitude, and reach the high twenties by midday. A fleece and a windproof layer over normal clothing handles both.\n\n## Colours\n\nNeutral tones. Avoid dark blue and black, which attract tsetse flies, and bright white, which is visible at distance.\n\n## Consistently forgotten\n\n- **Binoculars** — one pair per person, not shared. The single item that most improves a safari.\n- **A power bank** — camp generators often run only part of the day.\n- **Small denomination US dollars** — for tips. Notes printed before 2009 are frequently refused.\n- **Insect repellent with DEET** and antimalarials arranged before departure.\n- **A dust-proof bag** for your camera.\n\n## Not needed\n\nFull safari-brand outfits, a tripod, and more than two pairs of shoes.`,
      `## Die Gewichtsgrenze ist ernst gemeint\n\nKleinflugzeuge zwischen Camps erlauben meist 15 kg in einer weichen Tasche. Nicht 15 kg plus Handgepäck, und kein Hartschalenkoffer. Wenn Ihre Route einen Flug enthält, packen Sie von Anfang an nach dieser Zahl.\n\n## Schichten statt warmer Kleidung\n\nPirschfahrten starten vor Sonnenaufgang, wenn es im offenen Fahrzeug in der Höhe nahe dem Gefrierpunkt sein kann, und erreichen mittags fast dreißig Grad. Fleece plus Windjacke über normaler Kleidung deckt beides ab.\n\n## Farben\n\nNeutrale Töne. Dunkelblau und Schwarz ziehen Tsetsefliegen an, helles Weiß ist weithin sichtbar.\n\n## Regelmäßig vergessen\n\n- **Fernglas** — eines pro Person, nicht geteilt. Das Ausrüstungsstück mit dem größten Effekt.\n- **Powerbank** — Camp-Generatoren laufen oft nur zeitweise.\n- **US-Dollar in kleinen Scheinen** — für Trinkgeld. Noten von vor 2009 werden häufig abgelehnt.\n- **Insektenschutz mit DEET** und vorab organisierte Malariaprophylaxe.\n- **Staubdichte Tasche** für die Kamera.\n\n## Nicht nötig\n\nKomplette Safari-Markenausstattung, Stativ und mehr als zwei Paar Schuhe.`,
      `## La limite de poids est réelle\n\nLes avions légers entre camps autorisent en général 15 kg en sac souple. Pas 15 kg plus un bagage à main, et pas de valise rigide. Si votre itinéraire comprend un vol, préparez-vous à ce chiffre dès le départ.\n\n## Des couches, pas des vêtements chauds\n\nLes safaris partent avant le lever du soleil, quand il peut faire presque zéro en véhicule ouvert en altitude, et atteignent près de trente degrés à midi. Une polaire et un coupe-vent suffisent.\n\n## Les couleurs\n\nTons neutres. Évitez le bleu foncé et le noir, qui attirent les mouches tsé-tsé, et le blanc vif, visible de loin.\n\n## Les oublis fréquents\n\n- **Des jumelles** — une paire par personne. L’objet qui améliore le plus un safari.\n- **Une batterie externe** — les générateurs ne tournent souvent qu’une partie de la journée.\n- **Des petites coupures en dollars** — pour les pourboires. Les billets antérieurs à 2009 sont souvent refusés.\n- **Un répulsif au DEET** et un traitement antipaludique prévu avant le départ.\n- **Une housse anti-poussière** pour l’appareil photo.\n\n## Inutile\n\nUne panoplie de safari complète, un trépied, et plus de deux paires de chaussures.`,
      `## Il limite di peso è reale\n\nGli aerei leggeri tra i campi consentono in genere 15 kg in una borsa morbida. Non 15 kg più bagaglio a mano, e non in valigia rigida. Se l’itinerario prevede un volo, prepara i bagagli su quel numero fin dall’inizio.\n\n## Strati, non vestiti pesanti\n\nI game drive partono prima dell’alba, quando in quota su un veicolo aperto può essere quasi zero, e arrivano a quasi trenta gradi a mezzogiorno. Un pile e una giacca antivento bastano.\n\n## I colori\n\nToni neutri. Evita blu scuro e nero, che attirano le mosche tse-tse, e il bianco acceso, visibile da lontano.\n\n## Le dimenticanze ricorrenti\n\n- **Binocolo** — uno a testa, non condiviso. L’oggetto che migliora di più un safari.\n- **Power bank** — i generatori dei campi spesso funzionano solo parte del giorno.\n- **Dollari in banconote piccole** — per le mance. Le banconote precedenti al 2009 vengono spesso rifiutate.\n- **Repellente con DEET** e profilassi antimalarica organizzata prima della partenza.\n- **Custodia antipolvere** per la fotocamera.\n\n## Non serve\n\nUn completo da safari di marca, il treppiede e più di due paia di scarpe.`,
    ),
  },
  {
    key: 'entry-requirements',
    destination: null,
    category: null,
    readingMinutes: 3,
    sortOrder: 6,
    title: t(
      'Tanzania visas and entry requirements',
      'Visum und Einreise nach Tansania',
      'Visas et formalités d’entrée en Tanzanie',
      'Visti e requisiti d’ingresso in Tanzania',
    ),
    slug: t('tanzania-visa-requirements', 'tansania-visum-einreise', 'visa-tanzanie-formalites', 'visto-tanzania-requisiti'),
    excerpt: t(
      'What to arrange before you fly, and what you can do on arrival.',
      'Was Sie vor dem Abflug regeln müssen und was bei der Ankunft möglich ist.',
      'Ce qu’il faut préparer avant de partir et ce qui se règle à l’arrivée.',
      'Cosa organizzare prima di partire e cosa si può fare all’arrivo.',
    ),
    body: t(
      `> Requirements change. Confirm against the Tanzania Immigration Services Department and your own government's travel advice before booking.\n\n## Visas\n\nMost visitors need a visa. The ordinary tourist visa is typically single-entry and valid for up to 90 days. Applying online in advance through the official immigration portal is usually smoother than arriving without one, though visa on arrival is available at major airports for many nationalities.\n\nUS citizens are generally issued a multiple-entry visa at a higher fee.\n\n## Passport\n\nSix months validity beyond your arrival date, and at least one blank page.\n\n## Health\n\nA yellow fever certificate is required if you are arriving from, or have transited through, a country with risk of transmission. Coming directly from Europe or North America, it is usually not required — but transiting through certain African airports can trigger it, so check your specific routing.\n\nMalaria prophylaxis is recommended for most of the country. Arrange it with a travel clinic well before departure.\n\n## Zanzibar\n\nZanzibar requires all visitors to hold mandatory travel insurance purchased through its designated provider, in addition to any policy you already have. Buy it online before travelling.`,
      `> Bestimmungen ändern sich. Prüfen Sie vor der Buchung die Angaben der tansanischen Einwanderungsbehörde und die Reisehinweise Ihres Auswärtigen Amts.\n\n## Visum\n\nDie meisten Besucher benötigen ein Visum. Das gewöhnliche Touristenvisum gilt in der Regel für eine Einreise und bis zu 90 Tage. Die Online-Beantragung über das offizielle Portal verläuft meist reibungsloser als die Beantragung bei Ankunft, die an großen Flughäfen für viele Nationalitäten möglich ist.\n\nUS-Staatsangehörige erhalten üblicherweise ein Mehrfachvisum zu höherer Gebühr.\n\n## Reisepass\n\nSechs Monate Gültigkeit über das Einreisedatum hinaus und mindestens eine freie Seite.\n\n## Gesundheit\n\nEine Gelbfieberimpfbescheinigung ist erforderlich, wenn Sie aus einem Risikogebiet einreisen oder dort transitiert sind. Bei Direktflügen aus Europa ist sie meist nicht nötig — bestimmte afrikanische Transitflughäfen lösen die Pflicht jedoch aus. Prüfen Sie Ihre konkrete Route.\n\nMalariaprophylaxe wird für weite Teile des Landes empfohlen. Klären Sie das rechtzeitig mit einer reisemedizinischen Praxis.\n\n## Sansibar\n\nSansibar verlangt von allen Besuchern eine obligatorische Reiseversicherung über den dafür bestimmten Anbieter — zusätzlich zu einer bestehenden Police. Schließen Sie sie vor der Reise online ab.`,
      `> Les règles évoluent. Vérifiez auprès des services d’immigration tanzaniens et des conseils aux voyageurs de votre pays avant de réserver.\n\n## Visas\n\nLa plupart des visiteurs ont besoin d’un visa. Le visa touristique ordinaire est généralement à entrée unique et valable jusqu’à 90 jours. La demande en ligne sur le portail officiel est habituellement plus fluide que l’obtention à l’arrivée, possible dans les grands aéroports pour de nombreuses nationalités.\n\nLes ressortissants américains reçoivent en général un visa à entrées multiples, à un tarif plus élevé.\n\n## Passeport\n\nSix mois de validité après la date d’arrivée et au moins une page vierge.\n\n## Santé\n\nUn certificat de fièvre jaune est exigé si vous arrivez d’un pays à risque ou y avez transité. En provenance directe d’Europe, il n’est généralement pas requis — mais certains transits africains le déclenchent : vérifiez votre itinéraire précis.\n\nUne prophylaxie antipaludique est recommandée dans la majeure partie du pays. Organisez-la bien avant le départ.\n\n## Zanzibar\n\nZanzibar impose à tous les visiteurs une assurance voyage obligatoire souscrite auprès de son prestataire désigné, en plus de votre propre contrat. Achetez-la en ligne avant de partir.`,
      `> Le regole cambiano. Verifica presso i servizi immigrazione della Tanzania e gli avvisi di viaggio del tuo Paese prima di prenotare.\n\n## Visti\n\nLa maggior parte dei visitatori necessita di un visto. Il visto turistico ordinario è di norma a ingresso singolo e valido fino a 90 giorni. La domanda online sul portale ufficiale è di solito più semplice del visto all’arrivo, disponibile nei principali aeroporti per molte nazionalità.\n\nAi cittadini statunitensi viene generalmente rilasciato un visto a ingressi multipli, con tariffa più alta.\n\n## Passaporto\n\nSei mesi di validità oltre la data di arrivo e almeno una pagina libera.\n\n## Salute\n\nIl certificato di febbre gialla è richiesto se arrivi da un Paese a rischio o vi hai transitato. Arrivando direttamente dall’Europa di norma non serve — ma alcuni scali africani lo rendono obbligatorio: verifica il tuo itinerario.\n\nLa profilassi antimalarica è raccomandata in gran parte del Paese. Organizzala con un centro di medicina dei viaggi con largo anticipo.\n\n## Zanzibar\n\nZanzibar richiede a tutti i visitatori un’assicurazione di viaggio obbligatoria acquistata tramite il fornitore designato, in aggiunta a eventuali polizze già in essere. Acquistala online prima di partire.`,
    ),
  },
];
