/**
 * Demo packages.
 *
 * Prices are indicative of real Tanzanian market rates so the comparison and
 * filtering UI is exercised against believable numbers rather than round
 * placeholders. All rows carry is_demo = true.
 *
 * `t` packs the four locales positionally: [en, de, fr, it].
 */

const t = (en, de, fr, it) => ({ en, de, fr, it });

export const packages = [
  {
    slug: 'demo-serengeti-migration-7-day',
    business: 'demo-serengeti-plains-safaris',
    destinations: ['serengeti', 'ngorongoro'],
    categories: ['safaris'],
    days: 7, nights: 6, priceFrom: 3450, currency: 'USD', unit: 'per_person',
    maxGroup: 6, minTravelers: 2, featured: true,
    title: t(
      '7-Day Great Migration Safari',
      '7-tägige Safari zur Großen Tierwanderung',
      'Safari Grande Migration — 7 jours',
      'Safari Grande Migrazione — 7 giorni',
    ),
    summary: t(
      'Serengeti and Ngorongoro, with camp positioned for the month you travel.',
      'Serengeti und Ngorongoro, mit Camp passend zum Reisemonat.',
      'Serengeti et Ngorongoro, camp positionné selon votre mois de voyage.',
      'Serengeti e Ngorongoro, campo posizionato in base al mese di viaggio.',
    ),
    description: t(
      'Six nights across the Serengeti and the Ngorongoro Crater, with the camp chosen to match where the herds are in your travel month rather than a fixed lodge.',
      'Sechs Nächte in der Serengeti und am Ngorongoro-Krater. Das Camp wird nach dem tatsächlichen Standort der Herden im Reisemonat gewählt, nicht nach fester Lodge.',
      'Six nuits entre Serengeti et cratère du Ngorongoro, avec un camp choisi selon la position des troupeaux le mois de votre voyage.',
      'Sei notti tra Serengeti e cratere di Ngorongoro, con campo scelto in base alla posizione delle mandrie nel mese del viaggio.',
    ),
    inclusions: [
      [true, t('Park and crater fees', 'Park- und Kratergebühren', 'Droits de parc et de cratère', 'Tariffe parco e cratere')],
      [true, t('Private 4x4 with pop-up roof', 'Privater 4x4 mit Hubdach', '4x4 privé à toit ouvrant', '4x4 privato con tetto apribile')],
      [true, t('Full board at camps', 'Vollpension in den Camps', 'Pension complète en camp', 'Pensione completa nei campi')],
      [true, t('Airport transfers', 'Flughafentransfers', 'Transferts aéroport', 'Transfer aeroportuali')],
      [false, t('International flights', 'Internationale Flüge', 'Vols internationaux', 'Voli internazionali')],
      [false, t('Tanzania visa', 'Visum für Tansania', 'Visa tanzanien', 'Visto per la Tanzania')],
      [false, t('Tips and gratuities', 'Trinkgelder', 'Pourboires', 'Mance')],
    ],
  },
  {
    slug: 'demo-northern-circuit-5-day',
    business: 'demo-serengeti-plains-safaris',
    destinations: ['serengeti', 'ngorongoro', 'arusha'],
    categories: ['safaris'],
    days: 5, nights: 4, priceFrom: 2190, currency: 'USD', unit: 'per_person',
    maxGroup: 6, minTravelers: 2,
    title: t('5-Day Northern Circuit Classic', '5-tägiger Klassiker im Norden', 'Circuit nord classique — 5 jours', 'Circuito nord classico — 5 giorni'),
    summary: t(
      'The short version: Serengeti, Ngorongoro and Lake Manyara from Arusha.',
      'Die kurze Variante: Serengeti, Ngorongoro und Lake Manyara ab Arusha.',
      'La version courte : Serengeti, Ngorongoro et lac Manyara depuis Arusha.',
      'La versione breve: Serengeti, Ngorongoro e lago Manyara da Arusha.',
    ),
    description: t(
      'A compressed northern circuit for travelers with a week or less, covering the three headline parks without the long transfers of a longer itinerary.',
      'Ein verdichteter Nordcircuit für Reisende mit höchstens einer Woche — die drei wichtigsten Parks ohne lange Transferstrecken.',
      'Un circuit nord condensé pour une semaine ou moins, couvrant les trois parcs phares sans les longs transferts.',
      'Un circuito nord compatto per chi ha una settimana o meno, con i tre parchi principali senza lunghi trasferimenti.',
    ),
    inclusions: [
      [true, t('Park fees', 'Parkgebühren', 'Droits de parc', 'Tariffe parco')],
      [true, t('Shared 4x4 safari vehicle', 'Geteiltes 4x4-Safarifahrzeug', '4x4 partagé', '4x4 condiviso')],
      [true, t('Full board', 'Vollpension', 'Pension complète', 'Pensione completa')],
      [false, t('Flights', 'Flüge', 'Vols', 'Voli')],
    ],
  },
  {
    slug: 'demo-ngorongoro-crater-day-trip',
    business: 'demo-crater-highlands-expeditions',
    destinations: ['ngorongoro'],
    categories: ['safaris'],
    days: 1, nights: 0, priceFrom: 395, currency: 'USD', unit: 'per_person',
    maxGroup: 6, minTravelers: 2,
    title: t('Ngorongoro Crater Day Trip', 'Tagesausflug zum Ngorongoro-Krater', 'Excursion d’une journée au cratère', 'Escursione giornaliera al cratere'),
    summary: t(
      'Dawn descent, full day on the crater floor, back by evening.',
      'Abfahrt im Morgengrauen, ganzer Tag im Krater, abends zurück.',
      'Descente à l’aube, journée entière au fond du cratère, retour le soir.',
      'Discesa all’alba, giornata intera sul fondo del cratere, rientro in serata.',
    ),
    description: t(
      'Leaves Karatu before first light to be on the crater floor as it opens, when the cats are still active and before the vehicle traffic builds.',
      'Startet vor Sonnenaufgang in Karatu, um bei Öffnung im Krater zu sein — solange die Raubkatzen aktiv sind und bevor der Verkehr zunimmt.',
      'Départ de Karatu avant l’aube pour être au fond du cratère à l’ouverture, quand les félins sont actifs et avant l’affluence.',
      'Partenza da Karatu prima dell’alba per essere sul fondo del cratere all’apertura, quando i felini sono attivi e prima del traffico.',
    ),
    inclusions: [
      [true, t('Crater entry and vehicle fee', 'Kratereintritt und Fahrzeuggebühr', 'Entrée du cratère et véhicule', 'Ingresso cratere e veicolo')],
      [true, t('Picnic lunch', 'Lunchpaket', 'Déjeuner pique-nique', 'Pranzo al sacco')],
      [false, t('Accommodation', 'Unterkunft', 'Hébergement', 'Alloggio')],
    ],
  },
  {
    slug: 'demo-kilimanjaro-lemosho-8-day',
    business: 'demo-kilimanjaro-summit-guides',
    destinations: ['kilimanjaro'],
    categories: ['activities'],
    days: 8, nights: 7, priceFrom: 2650, currency: 'USD', unit: 'per_person',
    maxGroup: 12, minTravelers: 1, featured: true,
    title: t('Lemosho Route — 8 Days', 'Lemosho-Route — 8 Tage', 'Voie Lemosho — 8 jours', 'Via Lemosho — 8 giorni'),
    summary: t(
      'The highest-success Kilimanjaro route, with a full acclimatisation day.',
      'Die erfolgreichste Kilimandscharo-Route mit vollem Akklimatisierungstag.',
      'La voie du Kilimandjaro au meilleur taux de réussite, avec un jour d’acclimatation.',
      'La via del Kilimangiaro con il miglior tasso di successo, con un giorno di acclimatamento.',
    ),
    description: t(
      'Eight days on Lemosho, approaching from the west with a long high-altitude traverse before summit night. The extra day is the single biggest factor in reaching Uhuru Peak.',
      'Acht Tage auf der Lemosho-Route, Anstieg von Westen mit langer Höhenquerung vor der Gipfelnacht. Der zusätzliche Tag ist der wichtigste Faktor für den Gipfelerfolg.',
      'Huit jours sur Lemosho, approche par l’ouest avec une longue traversée en altitude avant la nuit du sommet. Le jour supplémentaire est le facteur déterminant.',
      'Otto giorni sulla Lemosho, avvicinamento da ovest con una lunga traversata in quota prima della notte di vetta. Il giorno extra è il fattore decisivo.',
    ),
    inclusions: [
      [true, t('Park fees and rescue fee', 'Park- und Rettungsgebühren', 'Droits de parc et de secours', 'Tariffe parco e soccorso')],
      [true, t('Guides, cook and porters', 'Guides, Koch und Träger', 'Guides, cuisinier et porteurs', 'Guide, cuoco e portatori')],
      [true, t('Tents, mess tent and mattresses', 'Zelte, Messzelt und Matratzen', 'Tentes, tente-mess et matelas', 'Tende, tenda mensa e materassi')],
      [true, t('Oximeter checks twice daily', 'Zweimal täglich Oximeter-Kontrolle', 'Contrôle oxymétrique deux fois par jour', 'Controllo con ossimetro due volte al giorno')],
      [false, t('Personal trekking gear', 'Persönliche Trekkingausrüstung', 'Équipement personnel', 'Attrezzatura personale')],
      [false, t('Crew tips', 'Trinkgeld für das Team', 'Pourboires de l’équipe', 'Mance per lo staff')],
    ],
  },
  {
    slug: 'demo-kilimanjaro-machame-7-day',
    business: 'demo-kilimanjaro-summit-guides',
    destinations: ['kilimanjaro'],
    categories: ['activities'],
    days: 7, nights: 6, priceFrom: 2150, currency: 'USD', unit: 'per_person',
    maxGroup: 12, minTravelers: 1,
    title: t('Machame Route — 7 Days', 'Machame-Route — 7 Tage', 'Voie Machame — 7 jours', 'Via Machame — 7 giorni'),
    summary: t(
      'The popular "Whiskey" route, steeper and busier than Lemosho.',
      'Die beliebte „Whiskey“-Route — steiler und stärker frequentiert als Lemosho.',
      'La célèbre voie « Whiskey », plus raide et plus fréquentée que Lemosho.',
      'La nota via "Whiskey", più ripida e frequentata della Lemosho.',
    ),
    description: t(
      'Seven days on Machame. Steeper profile and more traffic than Lemosho, but a strong climb-high-sleep-low pattern and a lower price.',
      'Sieben Tage auf der Machame-Route. Steileres Profil und mehr Betrieb als Lemosho, aber gutes Höhenprofil und günstigerer Preis.',
      'Sept jours sur Machame. Profil plus raide et plus de monde que Lemosho, mais un bon schéma d’acclimatation et un prix inférieur.',
      'Sette giorni sulla Machame. Profilo più ripido e più affollato della Lemosho, ma buon schema di acclimatamento e prezzo inferiore.',
    ),
    inclusions: [
      [true, t('Park fees', 'Parkgebühren', 'Droits de parc', 'Tariffe parco')],
      [true, t('Guides and porters', 'Guides und Träger', 'Guides et porteurs', 'Guide e portatori')],
      [false, t('Sleeping bag hire', 'Schlafsackmiete', 'Location de sac de couchage', 'Noleggio sacco a pelo')],
    ],
  },
  {
    slug: 'demo-nyerere-boat-fly-in-4-day',
    business: 'demo-southern-rivers-safari-co',
    destinations: ['nyerere'],
    categories: ['safaris'],
    days: 4, nights: 3, priceFrom: 1980, currency: 'USD', unit: 'per_person',
    maxGroup: 8, minTravelers: 2,
    title: t('Nyerere Fly-In — 4 Days', 'Nyerere Fly-in — 4 Tage', 'Nyerere en avion — 4 jours', 'Nyerere fly-in — 4 giorni'),
    summary: t(
      'Boat safaris on the Rufiji, walking safaris and no crowds.',
      'Bootssafaris auf dem Rufiji, Wandersafaris und keine Menschenmassen.',
      'Safaris en bateau sur le Rufiji, safaris à pied et aucune foule.',
      'Safari in barca sul Rufiji, safari a piedi e nessuna folla.',
    ),
    description: t(
      'Fly from Dar es Salaam into the southern circuit for three nights on the Rufiji, combining boat, vehicle and walking safaris.',
      'Flug ab Daressalam in den Süden, drei Nächte am Rufiji mit Boots-, Fahrzeug- und Wandersafaris.',
      'Vol depuis Dar es Salaam vers le circuit sud, trois nuits sur le Rufiji entre bateau, véhicule et marche.',
      'Volo da Dar es Salaam verso il circuito sud, tre notti sul Rufiji tra barca, veicolo e camminate.',
    ),
    inclusions: [
      [true, t('Return light aircraft flights', 'Hin- und Rückflug im Kleinflugzeug', 'Vols aller-retour en avion léger', 'Voli andata e ritorno con aereo leggero')],
      [true, t('Boat and walking safaris', 'Boots- und Wandersafaris', 'Safaris en bateau et à pied', 'Safari in barca e a piedi')],
      [true, t('Park fees', 'Parkgebühren', 'Droits de parc', 'Tariffe parco')],
      [false, t('Drinks', 'Getränke', 'Boissons', 'Bevande')],
    ],
  },
  {
    slug: 'demo-zanzibar-beach-7-night',
    business: 'demo-nungwi-beach-resort',
    destinations: ['zanzibar'],
    categories: ['hotels'],
    days: 8, nights: 7, priceFrom: 1120, currency: 'USD', unit: 'per_person',
    minTravelers: 2,
    title: t('7 Nights on the North Coast', '7 Nächte an der Nordküste', '7 nuits sur la côte nord', '7 notti sulla costa nord'),
    summary: t(
      'Beachfront half board with transfers, at the swimmable end of the island.',
      'Halbpension am Strand mit Transfers, am schwimmbaren Ende der Insel.',
      'Demi-pension en bord de plage avec transferts, du côté baignable de l’île.',
      'Mezza pensione fronte spiaggia con transfer, sul lato balneabile dell’isola.',
    ),
    description: t(
      'Seven nights half board in a beachfront room at Nungwi, including airport transfers and a sunset dhow cruise.',
      'Sieben Nächte Halbpension im Strandzimmer in Nungwi, inklusive Flughafentransfers und Dhau-Fahrt bei Sonnenuntergang.',
      'Sept nuits en demi-pension en chambre bord de plage à Nungwi, transferts et croisière en boutre au coucher du soleil inclus.',
      'Sette notti in mezza pensione in camera fronte spiaggia a Nungwi, transfer e crociera in dhow al tramonto inclusi.',
    ),
    inclusions: [
      [true, t('Half board', 'Halbpension', 'Demi-pension', 'Mezza pensione')],
      [true, t('Airport transfers', 'Flughafentransfers', 'Transferts aéroport', 'Transfer aeroportuali')],
      [true, t('Sunset dhow cruise', 'Dhau-Fahrt bei Sonnenuntergang', 'Croisière en boutre au coucher du soleil', 'Crociera in dhow al tramonto')],
      [false, t('Flights', 'Flüge', 'Vols', 'Voli')],
    ],
  },
  {
    slug: 'demo-stone-town-3-night',
    business: 'demo-stone-town-heritage-hotel',
    destinations: ['zanzibar'],
    categories: ['hotels'],
    days: 4, nights: 3, priceFrom: 420, currency: 'USD', unit: 'per_person',
    minTravelers: 1,
    title: t('3 Nights in Stone Town', '3 Nächte in Stone Town', '3 nuits à Stone Town', '3 notti a Stone Town'),
    summary: t(
      'Heritage room, spice farm visit and a guided walk through the old quarter.',
      'Historisches Zimmer, Gewürzfarm-Besuch und Altstadtführung.',
      'Chambre de caractère, visite d’une plantation d’épices et balade guidée.',
      'Camera storica, visita a una piantagione di spezie e passeggiata guidata.',
    ),
    description: t(
      'Three nights in the old quarter with a spice farm morning and a guided history walk, easily combined with a beach stay afterwards.',
      'Drei Nächte in der Altstadt mit Gewürzfarm-Vormittag und historischer Führung — gut mit anschließendem Strandaufenthalt kombinierbar.',
      'Trois nuits dans la vieille ville avec une matinée plantation d’épices et une balade historique, à combiner avec un séjour balnéaire.',
      'Tre notti nel centro storico con mattinata alle piantagioni di spezie e passeggiata storica, combinabile con un soggiorno al mare.',
    ),
    inclusions: [
      [true, t('Breakfast', 'Frühstück', 'Petit-déjeuner', 'Colazione')],
      [true, t('Spice farm tour', 'Gewürzfarm-Tour', 'Visite de plantation d’épices', 'Tour delle spezie')],
      [true, t('Guided Stone Town walk', 'Geführter Rundgang in Stone Town', 'Balade guidée à Stone Town', 'Passeggiata guidata a Stone Town')],
    ],
  },
  {
    slug: 'demo-mnemba-dive-package',
    business: 'demo-zanzibar-dive-centre',
    destinations: ['zanzibar'],
    categories: ['activities'],
    days: 3, nights: 0, priceFrom: 340, currency: 'USD', unit: 'per_person',
    maxGroup: 8, minTravelers: 1,
    title: t('Mnemba Atoll — 6 Dives', 'Mnemba-Atoll — 6 Tauchgänge', 'Atoll de Mnemba — 6 plongées', 'Atollo di Mnemba — 6 immersioni'),
    summary: t(
      'Six boat dives over three days, equipment included.',
      'Sechs Bootstauchgänge an drei Tagen, Ausrüstung inklusive.',
      'Six plongées en bateau sur trois jours, équipement inclus.',
      'Sei immersioni dalla barca in tre giorni, attrezzatura inclusa.',
    ),
    description: t(
      'Six guided boat dives on the Mnemba atoll reef over three days, suitable from Open Water upward, with full equipment hire included.',
      'Sechs geführte Bootstauchgänge am Mnemba-Riff an drei Tagen, ab Open Water geeignet, komplette Ausrüstung inklusive.',
      'Six plongées guidées sur le récif de Mnemba en trois jours, à partir du niveau Open Water, matériel complet inclus.',
      'Sei immersioni guidate sulla barriera di Mnemba in tre giorni, dal livello Open Water, attrezzatura completa inclusa.',
    ),
    inclusions: [
      [true, t('Six boat dives', 'Sechs Bootstauchgänge', 'Six plongées en bateau', 'Sei immersioni dalla barca')],
      [true, t('Full equipment hire', 'Komplette Ausrüstungsmiete', 'Location de matériel complet', 'Noleggio attrezzatura completa')],
      [true, t('Marine park fees', 'Meeresparkgebühren', 'Droits du parc marin', 'Tariffe parco marino')],
      [false, t('Certification course', 'Zertifizierungskurs', 'Cours de certification', 'Corso di certificazione')],
    ],
  },
  {
    slug: 'demo-usambara-3-day-trek',
    business: 'demo-usambara-hiking-collective',
    destinations: ['tanga'],
    categories: ['activities'],
    days: 3, nights: 2, priceFrom: 180, currency: 'USD', unit: 'per_person',
    maxGroup: 10, minTravelers: 2,
    title: t('Usambara Village Trek — 3 Days', 'Usambara-Dorftrek — 3 Tage', 'Trek des villages Usambara — 3 jours', 'Trek dei villaggi Usambara — 3 giorni'),
    summary: t(
      'Village-to-village walking with two nights in local guesthouses.',
      'Wandern von Dorf zu Dorf mit zwei Nächten in Dorfgasthäusern.',
      'Marche de village en village avec deux nuits chez l’habitant.',
      'Cammino di villaggio in villaggio con due notti in guesthouse locali.',
    ),
    description: t(
      'Three days walking the Usambara ridges between Lushoto and Mtae, staying in village guesthouses and eating with host families.',
      'Drei Tage Wandern auf den Usambara-Kämmen zwischen Lushoto und Mtae, Übernachtung in Dorfgasthäusern und Essen bei Gastfamilien.',
      'Trois jours de marche sur les crêtes des Usambara entre Lushoto et Mtae, nuits chez l’habitant et repas en famille.',
      'Tre giorni di cammino sulle creste degli Usambara tra Lushoto e Mtae, notti in guesthouse e pasti con le famiglie.',
    ),
    inclusions: [
      [true, t('Local guide', 'Lokaler Guide', 'Guide local', 'Guida locale')],
      [true, t('Guesthouse accommodation', 'Unterkunft in Gasthäusern', 'Hébergement chez l’habitant', 'Alloggio in guesthouse')],
      [true, t('All meals', 'Alle Mahlzeiten', 'Tous les repas', 'Tutti i pasti')],
    ],
  },
  {
    slug: 'demo-4x4-selfdrive-7-day',
    business: 'demo-northern-circuit-4x4-hire',
    destinations: ['arusha', 'serengeti', 'ngorongoro'],
    categories: ['car-rental'],
    days: 7, nights: 0, priceFrom: 1190, currency: 'USD', unit: 'per_vehicle',
    minTravelers: 1,
    title: t('7-Day Self-Drive 4x4', '7 Tage Selbstfahrer-4x4', '4x4 en autotour — 7 jours', '4x4 self-drive — 7 giorni'),
    summary: t(
      'Land Cruiser with rooftop tents, camping kit and unlimited mileage.',
      'Land Cruiser mit Dachzelten, Campingausrüstung und unbegrenzten Kilometern.',
      'Land Cruiser avec tentes de toit, matériel de camping et kilométrage illimité.',
      'Land Cruiser con tende da tetto, attrezzatura da campeggio e chilometraggio illimitato.',
    ),
    description: t(
      'Seven days with a fully equipped Land Cruiser: two rooftop tents, cooking kit, fridge, recovery gear and unlimited mileage across the northern circuit.',
      'Sieben Tage mit voll ausgestattetem Land Cruiser: zwei Dachzelte, Kochausrüstung, Kühlbox, Bergeausrüstung und unbegrenzte Kilometer im Nordcircuit.',
      'Sept jours avec un Land Cruiser tout équipé : deux tentes de toit, matériel de cuisine, réfrigérateur, kit de désensablage et kilométrage illimité.',
      'Sette giorni con un Land Cruiser completamente attrezzato: due tende da tetto, kit cucina, frigo, attrezzatura di recupero e chilometraggio illimitato.',
    ),
    inclusions: [
      [true, t('Unlimited mileage', 'Unbegrenzte Kilometer', 'Kilométrage illimité', 'Chilometraggio illimitato')],
      [true, t('Camping equipment', 'Campingausrüstung', 'Matériel de camping', 'Attrezzatura da campeggio')],
      [true, t('24/7 recovery support', 'Pannenhilfe rund um die Uhr', 'Assistance 24h/24', 'Assistenza 24/7')],
      [false, t('Fuel', 'Kraftstoff', 'Carburant', 'Carburante')],
      [false, t('Park entry fees', 'Parkeintritt', 'Droits d’entrée des parcs', 'Ingressi ai parchi')],
    ],
  },
  {
    slug: 'demo-airport-transfer-zanzibar',
    business: 'demo-coastal-transfers-tanzania',
    destinations: ['zanzibar'],
    categories: ['car-rental'],
    days: 1, nights: 0, priceFrom: 35, currency: 'USD', unit: 'per_vehicle',
    maxGroup: 4, minTravelers: 1,
    title: t('Zanzibar Airport Transfer', 'Flughafentransfer Sansibar', 'Transfert aéroport Zanzibar', 'Transfer aeroporto Zanzibar'),
    summary: t(
      'Fixed-price private transfer between the airport and any north-coast hotel.',
      'Privattransfer zum Festpreis zwischen Flughafen und Hotels an der Nordküste.',
      'Transfert privé à prix fixe entre l’aéroport et tout hôtel de la côte nord.',
      'Transfer privato a prezzo fisso tra aeroporto e hotel della costa nord.',
    ),
    description: t(
      'Private air-conditioned transfer with a fixed price regardless of flight delay, meeting you inside the terminal.',
      'Privater, klimatisierter Transfer zum Festpreis unabhängig von Flugverspätungen, Empfang im Terminal.',
      'Transfert privé climatisé à prix fixe quel que soit le retard du vol, accueil dans le terminal.',
      'Transfer privato con aria condizionata a prezzo fisso indipendentemente dai ritardi, accoglienza in aeroporto.',
    ),
    inclusions: [
      [true, t('Meet and greet in arrivals', 'Empfang im Ankunftsbereich', 'Accueil aux arrivées', 'Accoglienza agli arrivi')],
      [true, t('Air-conditioned vehicle', 'Klimatisiertes Fahrzeug', 'Véhicule climatisé', 'Veicolo climatizzato')],
    ],
  },
  {
    slug: 'demo-birding-day-arusha',
    business: 'demo-serengeti-birding-guide',
    destinations: ['arusha'],
    categories: ['tour-guides'],
    days: 1, nights: 0, priceFrom: 150, currency: 'USD', unit: 'per_group',
    maxGroup: 4, minTravelers: 1,
    title: t('Arusha Birding Day', 'Vogelbeobachtungstag Arusha', 'Journée ornithologique à Arusha', 'Giornata di birdwatching ad Arusha'),
    summary: t(
      'A full day around the Momella lakes with a specialist birding guide.',
      'Ein ganzer Tag an den Momella-Seen mit spezialisiertem Vogel-Guide.',
      'Une journée complète autour des lacs Momella avec un guide ornithologue.',
      'Una giornata intera intorno ai laghi Momella con una guida ornitologica.',
    ),
    description: t(
      'Guiding only, for travelers with their own vehicle. Flamingo, turaco and forest species around the Momella lakes and Ngurdoto crater.',
      'Nur Guiding, für Reisende mit eigenem Fahrzeug. Flamingos, Turakos und Waldarten an den Momella-Seen und am Ngurdoto-Krater.',
      'Guidage uniquement, pour voyageurs avec véhicule. Flamants, touracos et espèces forestières autour des lacs Momella.',
      'Solo guida, per viaggiatori con veicolo proprio. Fenicotteri, turaco e specie forestali intorno ai laghi Momella.',
    ),
    inclusions: [
      [true, t('Specialist guide for the day', 'Fachguide für einen Tag', 'Guide spécialisé pour la journée', 'Guida specializzata per la giornata')],
      [true, t('Shared spotting scope', 'Spektiv zur Mitbenutzung', 'Longue-vue partagée', 'Cannocchiale condiviso')],
      [false, t('Vehicle and park fees', 'Fahrzeug und Parkgebühren', 'Véhicule et droits de parc', 'Veicolo e tariffe parco')],
    ],
  },
  {
    slug: 'demo-stone-town-history-walk',
    business: 'demo-stone-town-walking-guides',
    destinations: ['zanzibar'],
    categories: ['tour-guides'],
    days: 1, nights: 0, priceFrom: 30, currency: 'USD', unit: 'per_person',
    maxGroup: 10, minTravelers: 1,
    title: t('Stone Town History Walk', 'Historischer Rundgang Stone Town', 'Balade historique à Stone Town', 'Passeggiata storica a Stone Town'),
    summary: t(
      'Two hours through the Swahili, Omani and colonial layers of the old town.',
      'Zwei Stunden durch die Suaheli-, omanischen und kolonialen Schichten der Altstadt.',
      'Deux heures à travers les strates swahilie, omanaise et coloniale.',
      'Due ore tra gli strati swahili, omaniti e coloniali della città vecchia.',
    ),
    description: t(
      'A two-hour walk covering the old dispensary, the former slave market site, the Omani fort and the merchant houses, ending at the seafront.',
      'Ein zweistündiger Rundgang zur alten Apotheke, zum ehemaligen Sklavenmarkt, zum omanischen Fort und den Kaufmannshäusern, mit Ende am Meer.',
      'Une marche de deux heures : ancien dispensaire, site de l’ancien marché aux esclaves, fort omanais et maisons de marchands, jusqu’au front de mer.',
      'Una passeggiata di due ore: vecchio dispensario, sito dell’ex mercato degli schiavi, forte omanita e case mercantili, fino al lungomare.',
    ),
    inclusions: [
      [true, t('Licensed guide', 'Lizenzierter Guide', 'Guide agréé', 'Guida autorizzata')],
      [false, t('Museum entry fees', 'Museumseintritt', 'Entrées des musées', 'Ingressi ai musei')],
    ],
  },
  {
    slug: 'demo-swahili-cooking-class',
    business: 'demo-forodhani-seafood-kitchen',
    destinations: ['zanzibar'],
    categories: ['restaurants'],
    days: 1, nights: 0, priceFrom: 55, currency: 'USD', unit: 'per_person',
    maxGroup: 8, minTravelers: 1,
    title: t('Swahili Cooking Class', 'Suaheli-Kochkurs', 'Cours de cuisine swahilie', 'Corso di cucina swahili'),
    summary: t(
      'Market shopping, then cook and eat a full Swahili meal.',
      'Einkauf auf dem Markt, dann ein komplettes Suaheli-Menü kochen und essen.',
      'Courses au marché, puis préparation et dégustation d’un repas swahili complet.',
      'Spesa al mercato, poi preparazione e degustazione di un pasto swahili completo.',
    ),
    description: t(
      'Starts at the market choosing fish and spices, then three hours in the kitchen cooking a coconut curry, chapati and a spiced dessert.',
      'Beginnt auf dem Markt mit der Auswahl von Fisch und Gewürzen, dann drei Stunden Küche: Kokos-Curry, Chapati und ein Gewürzdessert.',
      'Commence au marché pour choisir poisson et épices, puis trois heures en cuisine : curry au coco, chapati et dessert épicé.',
      'Inizia al mercato scegliendo pesce e spezie, poi tre ore in cucina: curry al cocco, chapati e un dolce speziato.',
    ),
    inclusions: [
      [true, t('Market tour and ingredients', 'Markttour und Zutaten', 'Visite du marché et ingrédients', 'Tour del mercato e ingredienti')],
      [true, t('The meal you cook', 'Das selbst gekochte Essen', 'Le repas que vous cuisinez', 'Il pasto che cucini')],
      [true, t('Recipe cards to take home', 'Rezeptkarten zum Mitnehmen', 'Fiches recettes à emporter', 'Ricette da portare a casa')],
    ],
  },
  {
    slug: 'demo-arusha-street-food-evening',
    business: 'demo-arusha-street-food-tours',
    destinations: ['arusha'],
    categories: ['restaurants'],
    days: 1, nights: 0, priceFrom: 40, currency: 'USD', unit: 'per_person',
    maxGroup: 8, minTravelers: 2,
    title: t('Arusha Street Food Evening', 'Street-Food-Abend in Arusha', 'Soirée street food à Arusha', 'Serata street food ad Arusha'),
    summary: t(
      'Six stops across the night market with a guide who explains each dish.',
      'Sechs Stationen über den Nachtmarkt mit einem Guide, der jedes Gericht erklärt.',
      'Six étapes au marché de nuit avec un guide qui explique chaque plat.',
      'Sei tappe nel mercato notturno con una guida che spiega ogni piatto.',
    ),
    description: t(
      'Three hours and six stops, from mishkaki skewers to chipsi mayai, with enough food to replace dinner. Vegetarian route available.',
      'Drei Stunden, sechs Stationen — von Mishkaki-Spießen bis Chipsi Mayai, ausreichend als Abendessen. Vegetarische Variante möglich.',
      'Trois heures et six étapes, des brochettes mishkaki au chipsi mayai, de quoi remplacer le dîner. Parcours végétarien disponible.',
      'Tre ore e sei tappe, dagli spiedini mishkaki al chipsi mayai, abbastanza da sostituire la cena. Disponibile percorso vegetariano.',
    ),
    inclusions: [
      [true, t('All food tastings', 'Alle Verkostungen', 'Toutes les dégustations', 'Tutte le degustazioni')],
      [true, t('English-speaking guide', 'Englischsprachiger Guide', 'Guide anglophone', 'Guida in inglese')],
      [false, t('Alcoholic drinks', 'Alkoholische Getränke', 'Boissons alcoolisées', 'Bevande alcoliche')],
    ],
  },
];
