import type { Locale } from '@/i18n/routing';
import type { DestinationSummary, CategoryWithCount } from '@/lib/queries/taxonomy';
import type { BusinessCard } from '@/lib/queries/businesses';
import type { GuideCard } from '@/lib/queries/guides';
import type { HeroFrame } from '@/components/home/hero-backdrop';
import type { SiteFacts } from '@/lib/queries/site-facts';
import { CURATED_REGIONAL_BUSINESSES } from '@/lib/queries/curated-regional-businesses';

export const CURATED_HERO_FRAMES: HeroFrame[] = [
  {
    src: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80',
    label: 'Serengeti National Park',
  },
  {
    src: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=1920&q=80',
    label: 'Mount Kilimanjaro',
  },
  {
    src: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1920&q=80',
    label: 'Zanzibar Archipelago',
  },
  {
    src: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1920&q=80',
    label: 'Ngorongoro Crater',
  },
  {
    src: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1920&q=80',
    label: 'Tarangire Savanna',
  },
];

export const CURATED_DESTINATIONS: Record<Locale, DestinationSummary[]> = {
  en: [
    {
      id: 'dest-serengeti',
      key: 'serengeti',
      slug: 'serengeti',
      name: 'Serengeti',
      summary: 'Endless golden plains and the world’s greatest wildlife migration spectacle.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ngorongoro',
      key: 'ngorongoro',
      slug: 'ngorongoro',
      name: 'Ngorongoro Crater',
      summary: 'A dramatic unbroken volcanic caldera harboring 25,000 resident animals.',
      coverImageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-kilimanjaro',
      key: 'kilimanjaro',
      slug: 'kilimanjaro',
      name: 'Mount Kilimanjaro',
      summary: 'The roof of Africa rising 5,895 meters above the equatorial savanna.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-zanzibar',
      key: 'zanzibar',
      slug: 'zanzibar',
      name: 'Zanzibar Island',
      summary: 'Powder-white beaches, turquoise lagoons, and historic UNESCO Stone Town.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-tarangire',
      key: 'tarangire',
      slug: 'tarangire',
      name: 'Tarangire National Park',
      summary: 'Iconic ancient baobab trees and Tanzania’s largest density of elephant herds.',
      coverImageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-manyara',
      key: 'lake-manyara',
      slug: 'lake-manyara',
      name: 'Lake Manyara',
      summary: 'Shimmering soda lake famous for pink flamingos and legendary tree-climbing lions.',
      coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ruaha',
      key: 'ruaha',
      slug: 'ruaha',
      name: 'Ruaha National Park',
      summary: 'Rugged southern wilderness with colossal lion prides and untouched river valleys.',
      coverImageUrl: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
    {
      id: 'dest-nyerere',
      key: 'nyerere',
      slug: 'nyerere',
      name: 'Nyerere (Selous)',
      summary: 'Africa’s largest wildlife sanctuary with unforgettable Rufiji riverboat safaris.',
      coverImageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
  ],
  de: [
    {
      id: 'dest-serengeti',
      key: 'serengeti',
      slug: 'serengeti',
      name: 'Serengeti',
      summary: 'Endlose Steppen und das größte Wildtierspektakel der Erde.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ngorongoro',
      key: 'ngorongoro',
      slug: 'ngorongoro-krater',
      name: 'Ngorongoro-Krater',
      summary: 'Eingestürzter Vulkan mit 25.000 Großtieren auf engem Raum.',
      coverImageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-kilimanjaro',
      key: 'kilimanjaro',
      slug: 'kilimandscharo',
      name: 'Kilimandscharo',
      summary: 'Das Dach Afrikas mit 5.895 Metern Höhe über der Savanne.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-zanzibar',
      key: 'zanzibar',
      slug: 'sansibar',
      name: 'Sansibar',
      summary: 'Weiße Strände, türkisfarbenes Meer und historische Gewürzinsel.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-tarangire',
      key: 'tarangire',
      slug: 'tarangire',
      name: 'Tarangire-Nationalpark',
      summary: 'Uralte Baobab-Bäume und riesige Elefantenherden.',
      coverImageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-manyara',
      key: 'lake-manyara',
      slug: 'lake-manyara',
      name: 'Lake Manyara',
      summary: 'Flamingos am Sodasee und baumkletternde Löwen.',
      coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ruaha',
      key: 'ruaha',
      slug: 'ruaha',
      name: 'Ruaha-Nationalpark',
      summary: 'Unberührte südliche Wildnis mit riesigen Löwenrudeln.',
      coverImageUrl: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
    {
      id: 'dest-nyerere',
      key: 'nyerere',
      slug: 'nyerere',
      name: 'Nyerere (Selous)',
      summary: 'Afrikas größtes Wildreservat mit Bootssafaris auf dem Rufiji-Fluss.',
      coverImageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
  ],
  fr: [
    {
      id: 'dest-serengeti',
      key: 'serengeti',
      slug: 'serengeti',
      name: 'Serengeti',
      summary: 'Plaines infinies et la plus grandiose migration animale de la planète.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ngorongoro',
      key: 'ngorongoro',
      slug: 'ngorongoro',
      name: 'Cratère du Ngorongoro',
      summary: 'Une caldeira volcanique intacte abritant plus de 25 000 animaux résidents.',
      coverImageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-kilimanjaro',
      key: 'kilimanjaro',
      slug: 'kilimandjaro',
      name: 'Mont Kilimandjaro',
      summary: 'Le toit de l’Afrique culminant à 5 895 mètres au-dessus de la savane.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-zanzibar',
      key: 'zanzibar',
      slug: 'zanzibar',
      name: 'Zanzibar',
      summary: 'Plages immaculées, lagons turquoise et ruelles historiques de Stone Town.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-tarangire',
      key: 'tarangire',
      slug: 'tarangire',
      name: 'Parc National de Tarangire',
      summary: 'Baobabs centenaires et plus grande concentration d’éléphants du pays.',
      coverImageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-manyara',
      key: 'lake-manyara',
      slug: 'lac-manyara',
      name: 'Lac Manyara',
      summary: 'Flamants roses au bord du lac et célèbres lions grimpeurs d’arbres.',
      coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ruaha',
      key: 'ruaha',
      slug: 'ruaha',
      name: 'Parc National de Ruaha',
      summary: 'Nature sauvage du sud et redoutables hardes de lions.',
      coverImageUrl: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
    {
      id: 'dest-nyerere',
      key: 'nyerere',
      slug: 'nyerere',
      name: 'Nyerere (Selous)',
      summary: 'Plus grande réserve de faune d’Afrique avec safaris en bateau sur le Rufiji.',
      coverImageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
  ],
  it: [
    {
      id: 'dest-serengeti',
      key: 'serengeti',
      slug: 'serengeti',
      name: 'Serengeti',
      summary: 'Sconfinate pianure dorate e la più grande migrazione animale al mondo.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ngorongoro',
      key: 'ngorongoro',
      slug: 'ngorongoro',
      name: 'Cratere di Ngorongoro',
      summary: 'Antica caldera vulcanica intatta con oltre 25.000 animali selvatici.',
      coverImageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-kilimanjaro',
      key: 'kilimanjaro',
      slug: 'kilimangiaro',
      name: 'Monte Kilimangiaro',
      summary: 'Il tetto d’Africa che si innalza per 5.895 metri sopra la savana.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-zanzibar',
      key: 'zanzibar',
      slug: 'zanzibar',
      name: 'Zanzibar',
      summary: 'Spiagge coralline bianche, acque turchesi e la storica Stone Town.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-tarangire',
      key: 'tarangire',
      slug: 'tarangire',
      name: 'Parco Nazionale di Tarangire',
      summary: 'Giganteschi baobab secolari e imponenti branchi di elefanti.',
      coverImageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-manyara',
      key: 'lake-manyara',
      slug: 'lago-manyara',
      name: 'Lago Manyara',
      summary: 'Fenicotteri rosa sul lago e i celebri leoni arboricoli.',
      coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'dest-ruaha',
      key: 'ruaha',
      slug: 'ruaha',
      name: 'Parco Nazionale di Ruaha',
      summary: 'Natura selvaggia e autentica nel sud della Tanzania.',
      coverImageUrl: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
    {
      id: 'dest-nyerere',
      key: 'nyerere',
      slug: 'nyerere',
      name: 'Nyerere (Selous)',
      summary: 'La più vasta area protetta d’Africa con safari in barca sul fiume Rufiji.',
      coverImageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
    },
  ],
};

export const CURATED_CATEGORIES: Record<Locale, CategoryWithCount[]> = {
  en: [
    {
      id: 'cat-safaris',
      key: 'safaris',
      slug: 'safaris',
      name: 'Safaris & Wildlife Tours',
      nameSingular: 'Safari Operator',
      summary: 'Guided game drives across the Serengeti, Ngorongoro, and Tarangire.',
      comboHeading: 'Safari Tours',
      icon: 'binoculars',
      businessCount: 834,
    },
    {
      id: 'cat-lodges',
      key: 'lodges',
      slug: 'lodges',
      name: 'Lodges & Tented Camps',
      nameSingular: 'Lodge & Camp',
      summary: 'From eco-luxury savanna tents to cliffside volcanic crater suites.',
      comboHeading: 'Places to Stay',
      icon: 'home',
      businessCount: 312,
    },
    {
      id: 'cat-trekking',
      key: 'trekking',
      slug: 'trekking',
      name: 'Mount Kilimanjaro Trekking',
      nameSingular: 'Mountain Guide',
      summary: 'Certified mountain crews for Kilimanjaro, Mount Meru, and Ol Doinyo Lengai.',
      comboHeading: 'Mountain Climbs',
      icon: 'mountain',
      businessCount: 168,
    },
    {
      id: 'cat-beach',
      key: 'beach',
      slug: 'beach',
      name: 'Beach & Marine Safaris',
      nameSingular: 'Marine Operator',
      summary: 'Zanzibar, Pemba & Mafia dhow cruises, snorkeling reefs, and whale sharks.',
      comboHeading: 'Coastal Activities',
      icon: 'waves',
      businessCount: 124,
    },
    {
      id: 'cat-cultural',
      key: 'cultural',
      slug: 'cultural',
      name: 'Cultural & Community Tours',
      nameSingular: 'Cultural Guide',
      summary: 'Authentic Maasai bomas, Hadzabe hunter-gatherers, and coffee farm walks.',
      comboHeading: 'Cultural Experiences',
      icon: 'users',
      businessCount: 86,
    },
    {
      id: 'cat-transport',
      key: 'transport',
      slug: 'transport',
      name: 'Safari Vehicles & Transfers',
      nameSingular: 'Transport Provider',
      summary: 'Custom pop-up roof 4x4 Land Cruisers and Kilimanjaro airport pickups.',
      comboHeading: 'Transport Services',
      icon: 'car',
      businessCount: 78,
    },
  ],
  de: [
    {
      id: 'cat-safaris',
      key: 'safaris',
      slug: 'safaris',
      name: 'Safaris & Wildtier-Touren',
      nameSingular: 'Safari-Veranstalter',
      summary: 'Geführte Pirschfahrten in Serengeti, Ngorongoro und Tarangire.',
      comboHeading: 'Safari-Touren',
      icon: 'binoculars',
      businessCount: 834,
    },
    {
      id: 'cat-lodges',
      key: 'lodges',
      slug: 'lodges',
      name: 'Lodges & Zeltcamps',
      nameSingular: 'Lodge & Camp',
      summary: 'Von Öko-Luxus-Zelten in der Savanne bis zu Krater-Lodges.',
      comboHeading: 'Unterkünfte',
      icon: 'home',
      businessCount: 312,
    },
    {
      id: 'cat-trekking',
      key: 'trekking',
      slug: 'trekking',
      name: 'Kilimandscharo-Besteigungen',
      nameSingular: 'Bergführer',
      summary: 'Zertifizierte Berg-Crews für Kilimandscharo und Mount Meru.',
      comboHeading: 'Bergtouren',
      icon: 'mountain',
      businessCount: 168,
    },
    {
      id: 'cat-beach',
      key: 'beach',
      slug: 'beach',
      name: 'Strand & Meeres-Safaris',
      nameSingular: 'Meeres-Guide',
      summary: 'Sansibar-Dau-Fahrten, Schnorcheln und Walhaie bei Mafia Island.',
      comboHeading: 'Küstenerlebnisse',
      icon: 'waves',
      businessCount: 124,
    },
    {
      id: 'cat-cultural',
      key: 'cultural',
      slug: 'cultural',
      name: 'Kultur- & Dorftouren',
      nameSingular: 'Kulturführer',
      summary: 'Authentische Massai-Bomas und Hadzabe-Begegnungen.',
      comboHeading: 'Kulturtouren',
      icon: 'users',
      businessCount: 86,
    },
    {
      id: 'cat-transport',
      key: 'transport',
      slug: 'transport',
      name: 'Safari-Fahrzeuge & Transfers',
      nameSingular: 'Fahrzeugvermieter',
      summary: 'Speziell umgebaute 4x4 Land Cruiser und Flughafentransfers.',
      comboHeading: 'Fahrdienste',
      icon: 'car',
      businessCount: 78,
    },
  ],
  fr: [
    {
      id: 'cat-safaris',
      key: 'safaris',
      slug: 'safaris',
      name: 'Safaris & Circuits Animaliers',
      nameSingular: 'Opérateur Safari',
      summary: 'Safaris guidés au Serengeti, au cratère du Ngorongoro et à Tarangire.',
      comboHeading: 'Circuits Safari',
      icon: 'binoculars',
      businessCount: 834,
    },
    {
      id: 'cat-lodges',
      key: 'lodges',
      slug: 'lodges',
      name: 'Lodges & Camps de Toile',
      nameSingular: 'Lodge & Camp',
      summary: 'Du camp éco-luxe sous tente aux suites sur la crête du cratère.',
      comboHeading: 'Hébergements',
      icon: 'home',
      businessCount: 312,
    },
    {
      id: 'cat-trekking',
      key: 'trekking',
      slug: 'trekking',
      name: 'Ascension du Kilimandjaro',
      nameSingular: 'Guide de Montagne',
      summary: 'Équipes de montagne certifiées pour le Kilimandjaro et le mont Meru.',
      comboHeading: 'Treks & Ascensions',
      icon: 'mountain',
      businessCount: 168,
    },
    {
      id: 'cat-beach',
      key: 'beach',
      slug: 'beach',
      name: 'Plages & Activités Marines',
      nameSingular: 'Activités Marines',
      summary: 'Excursions en dhow à Zanzibar, plongée corallienne et requins-baleines.',
      comboHeading: 'Activités Côtières',
      icon: 'waves',
      businessCount: 124,
    },
    {
      id: 'cat-cultural',
      key: 'cultural',
      slug: 'cultural',
      name: 'Tours Culturels & Rencontres',
      nameSingular: 'Guide Culturel',
      summary: 'Villages Masaï traditionnels, chasseurs Hadzabe et plantations de café.',
      comboHeading: 'Expériences Culturelles',
      icon: 'users',
      businessCount: 86,
    },
    {
      id: 'cat-transport',
      key: 'transport',
      slug: 'transport',
      name: 'Véhicules 4x4 & Transferts',
      nameSingular: 'Transporteur',
      summary: 'Land Cruisers 4x4 avec toit ouvrant et transferts aéroports.',
      comboHeading: 'Services de Transport',
      icon: 'car',
      businessCount: 78,
    },
  ],
  it: [
    {
      id: 'cat-safaris',
      key: 'safaris',
      slug: 'safaris',
      name: 'Safari & Tour Naturalistici',
      nameSingular: 'Operatore Safari',
      summary: 'Game drive guidati nel Serengeti, Ngorongoro e Tarangire.',
      comboHeading: 'Tour Safari',
      icon: 'binoculars',
      businessCount: 834,
    },
    {
      id: 'cat-lodges',
      key: 'lodges',
      slug: 'lodges',
      name: 'Lodge & Campi Tendati',
      nameSingular: 'Lodge & Campo',
      summary: 'Tende di lusso nella savana ed eleganti suite panoramiche.',
      comboHeading: 'Alloggi',
      icon: 'home',
      businessCount: 312,
    },
    {
      id: 'cat-trekking',
      key: 'trekking',
      slug: 'trekking',
      name: 'Trekking sul Kilimangiaro',
      nameSingular: 'Guida Alpina',
      summary: 'Guide esperte per scalare il Kilimangiaro e il Monte Meru.',
      comboHeading: 'Trekking di Montagna',
      icon: 'mountain',
      businessCount: 168,
    },
    {
      id: 'cat-beach',
      key: 'beach',
      slug: 'beach',
      name: 'Mare & Safari Marini',
      nameSingular: 'Operatore Marino',
      summary: 'Crociera in dhow a Zanzibar, barriere coralline e squali balena a Mafia.',
      comboHeading: 'Attività Marine',
      icon: 'waves',
      businessCount: 124,
    },
    {
      id: 'cat-cultural',
      key: 'cultural',
      slug: 'cultural',
      name: 'Tour Culturali & Comunità',
      nameSingular: 'Guida Culturale',
      summary: 'Incontri autentici con i Maasai, Hadzabe e tour delle spezie.',
      comboHeading: 'Esperienze Culturali',
      icon: 'users',
      businessCount: 86,
    },
    {
      id: 'cat-transport',
      key: 'transport',
      slug: 'transport',
      name: 'Noleggio 4x4 & Trasferimenti',
      nameSingular: 'Fornitore Trasporti',
      summary: 'Land Cruiser 4x4 equipaggiati da safari e transfer aeroportuali.',
      comboHeading: 'Trasporti',
      icon: 'car',
      businessCount: 78,
    },
  ],
};

export const CURATED_BUSINESSES: BusinessCard[] = CURATED_REGIONAL_BUSINESSES;

export const CURATED_GUIDES: Record<Locale, GuideCard[]> = {
  en: [
    {
      id: 'guide-migration-timing',
      slug: 'serengeti-great-migration-timing',
      title: 'Serengeti Great Migration: Month-by-Month Location Guide',
      excerpt:
        'Where the two million wildebeest and zebras actually are each season — from Ndutu calving in February to the Mara River crossings in August.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 8,
      publishedAt: '2026-06-15',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-kilimanjaro-routes',
      slug: 'kilimanjaro-routes-compared',
      title: 'Climbing Kilimanjaro: Machame, Lemosho, and Rongai Compared',
      excerpt:
        'Acclimatization profiles, summit success rates, scenic highlights, and how to choose the right trail for your physical fitness level.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 11,
      publishedAt: '2026-07-02',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-zanzibar-beaches',
      slug: 'zanzibar-beach-guide',
      title: 'The Real Zanzibar: Nungwi, Kendwa, Paje, and Stone Town Secrets',
      excerpt:
        'Tidal differences, swimming conditions, dhow sailing logistics, and how to combine a bush safari with an island escape.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 6,
      publishedAt: '2026-08-10',
      isFeatured: true,
      isDemo: false,
    },
  ],
  de: [
    {
      id: 'guide-migration-timing',
      slug: 'serengeti-tierwanderung-monatsguide',
      title: 'Große Tierwanderung in der Serengeti: Der Monats-Leitfaden',
      excerpt:
        'Wo sich die zwei Millionen Gnus und Zebras in den einzelnen Monaten aufhalten – von der Kalbungszeit bis zu den Flussüberquerungen.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 8,
      publishedAt: '2026-06-15',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-kilimanjaro-routes',
      slug: 'kilimandscharo-routen-vergleich',
      title: 'Kilimandscharo-Routen im Vergleich: Machame, Lemosho & Marangu',
      excerpt:
        'Akklimatisierungsprofile, Gipfelerfolgsquoten und Tipps zur Wahl der passenden Route für die Besteigung.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 11,
      publishedAt: '2026-07-02',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-zanzibar-beaches',
      slug: 'sansibar-strand-guide',
      title: 'Sansibar entdecken: Strände, Gezeiten und Stone Town Tipps',
      excerpt:
        'Gezeitenunterschiede, Schwimmbedingungen und wie Sie eine Busch-Safari ideal mit Badeurlaub kombinieren.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 6,
      publishedAt: '2026-08-10',
      isFeatured: true,
      isDemo: false,
    },
  ],
  fr: [
    {
      id: 'guide-migration-timing',
      slug: 'serengeti-grande-migration-saisons',
      title: 'Grande Migration au Serengeti : Guide Saison par Saison',
      excerpt:
        'Où se trouvent les troupeaux de gnous et zèbres au fil des mois, des naissances au sud aux traversées de la rivière Mara.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 8,
      publishedAt: '2026-06-15',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-kilimanjaro-routes',
      slug: 'kilimandjaro-choisir-sa-voie',
      title: 'Ascension du Kilimandjaro : Comparatif des Voies Machame et Lemosho',
      excerpt:
        'Profils d’acclimatation, taux de réussite au sommet et conseils d’équipement pour réussir votre ascension.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 11,
      publishedAt: '2026-07-02',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-zanzibar-beaches',
      slug: 'zanzibar-guide-plages',
      title: 'Zanzibar : Choisir sa Plage entre Nungwi, Paje et Stone Town',
      excerpt:
        'Marées, spots de baignade, plongée sur l’atoll de Mnemba et séjour combiné safari-plage.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 6,
      publishedAt: '2026-08-10',
      isFeatured: true,
      isDemo: false,
    },
  ],
  it: [
    {
      id: 'guide-migration-timing',
      slug: 'serengeti-grande-migrazione-periodi',
      title: 'Grande Migrazione nel Serengeti: Guida Mese per Mese',
      excerpt:
        'La rotta precisa degli gnu e delle zebre nelle diverse stagioni, dalle nascite di Ndutu ai guadi del fiume Mara.',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 8,
      publishedAt: '2026-06-15',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-kilimanjaro-routes',
      slug: 'kilimangiaro-confronto-percorsi',
      title: 'Scalare il Kilimangiaro: Quale Via Scegliere tra Machame e Lemosho',
      excerpt:
        'Tassi di acclimatazione, dislivelli, panorami e consigli pratici per raggiungere la vetta a 5.895 metri.',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 11,
      publishedAt: '2026-07-02',
      isFeatured: true,
      isDemo: false,
    },
    {
      id: 'guide-zanzibar-beaches',
      slug: 'zanzibar-guida-alle-spiagge',
      title: 'Zanzibar: Le Migliori Spiagge tra Nungwi, Paje e Stone Town',
      excerpt:
        'Maree, reef corallini, escursioni in barca e come combinare il safari nella savana con il mare di Zanzibar.',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      readingMinutes: 6,
      publishedAt: '2026-08-10',
      isFeatured: true,
      isDemo: false,
    },
  ],
};

export type EventCard = {
  id: string;
  key: string;
  kind: string;
  name: string;
  slug: string;
  summary: string | null;
  advice: string | null;
  typicalMonth: number | null;
  nextStart: string | null;
  nextEnd: string | null;
  countryCode: string | null;
  website: string | null;
  destination: { name: string; slug: string } | null;
};

export const CURATED_SITE_FACTS: SiteFacts = {
  operators: 1329,
  claimed: 412,
  verified: 986,
  destinations: 46,
  guides: 38,
  seasonality: 552,
};

export type CuratedCoveredCountry = {
  code: string;
  name: string;
  destinationCount: number;
};

export type CuratedCountryWithBusinesses = CuratedCoveredCountry & { businessCount: number };

export const CURATED_COVERED_COUNTRIES: CuratedCoveredCountry[] = [
  { code: 'TZ', name: 'Tanzania', destinationCount: 28 },
  { code: 'KE', name: 'Kenya', destinationCount: 12 },
  { code: 'UG', name: 'Uganda', destinationCount: 6 },
  { code: 'RW', name: 'Rwanda', destinationCount: 4 },
];

export const CURATED_COUNTRIES_WITH_BUSINESSES: CuratedCountryWithBusinesses[] = [
  { code: 'TZ', name: 'Tanzania', destinationCount: 28, businessCount: 980 },
  { code: 'KE', name: 'Kenya', destinationCount: 12, businessCount: 280 },
  { code: 'UG', name: 'Uganda', destinationCount: 6, businessCount: 85 },
  { code: 'RW', name: 'Rwanda', destinationCount: 4, businessCount: 42 },
];

export type CuratedRegionOption = {
  id: string;
  slug: string;
  name: string;
  countryCode: string;
};

export type CuratedRegionGroup = {
  countryCode: string;
  countryName: string;
  regions: CuratedRegionOption[];
};

export const CURATED_REGION_GROUPS: CuratedRegionGroup[] = [
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    regions: [
      { id: 'reg-arusha', slug: 'arusha', name: 'Arusha', countryCode: 'TZ' },
      { id: 'reg-kilimanjaro', slug: 'kilimanjaro', name: 'Kilimanjaro', countryCode: 'TZ' },
      { id: 'reg-zanzibar', slug: 'zanzibar-mjini-magharibi', name: 'Zanzibar Urban/West', countryCode: 'TZ' },
      { id: 'reg-dar', slug: 'dar-es-salaam', name: 'Dar es Salaam', countryCode: 'TZ' },
      { id: 'reg-mara', slug: 'mara', name: 'Mara (Serengeti)', countryCode: 'TZ' },
      { id: 'reg-manyara', slug: 'manyara', name: 'Manyara', countryCode: 'TZ' },
    ],
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    regions: [
      { id: 'reg-nairobi', slug: 'nairobi', name: 'Nairobi', countryCode: 'KE' },
      { id: 'reg-narok', slug: 'narok-masai-mara', name: 'Narok (Masai Mara)', countryCode: 'KE' },
      { id: 'reg-mombasa', slug: 'mombasa-coast-diani', name: 'Mombasa & Coast (Diani)', countryCode: 'KE' },
      { id: 'reg-kajiado', slug: 'kajiado-amboseli', name: 'Kajiado (Amboseli)', countryCode: 'KE' },
      { id: 'reg-laikipia', slug: 'laikipia-mount-kenya', name: 'Laikipia & Mount Kenya', countryCode: 'KE' },
      { id: 'reg-nakuru', slug: 'nakuru', name: 'Nakuru & Great Rift', countryCode: 'KE' },
    ],
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    regions: [
      { id: 'reg-central-ug', slug: 'central-kampala-entebbe', name: 'Central (Kampala & Entebbe)', countryCode: 'UG' },
      { id: 'reg-kigezi', slug: 'kigezi-bwindi', name: 'Kigezi (Bwindi Impenetrable)', countryCode: 'UG' },
      { id: 'reg-eastern-ug', slug: 'eastern-jinja-nile', name: 'Eastern (Jinja & Nile)', countryCode: 'UG' },
      { id: 'reg-western-ug', slug: 'western-queen-elizabeth', name: 'Western (Queen Elizabeth)', countryCode: 'UG' },
    ],
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    regions: [
      { id: 'reg-kigali', slug: 'kigali-city', name: 'Kigali City', countryCode: 'RW' },
      { id: 'reg-northern-rw', slug: 'northern-musanze-volcanoes', name: 'Northern (Musanze / Volcanoes)', countryCode: 'RW' },
      { id: 'reg-western-rw', slug: 'western-lake-kivu-rubavu', name: 'Western (Lake Kivu / Rubavu)', countryCode: 'RW' },
      { id: 'reg-southern-rw', slug: 'southern-nyungwe', name: 'Southern (Nyungwe Forest)', countryCode: 'RW' },
    ],
  },
];

export type CuratedPackageCard = {
  id: string;
  slug: string;
  title: string;
  summary: string | null;
  durationDays: number | null;
  durationNights: number | null;
  priceFrom: number | null;
  currency: string;
  priceUnit: string;
  coverImageUrl: string | null;
  isFeatured: boolean;
  isDemo: boolean;
  business: { slug: string; name: string; isVerified: boolean } | null;
  visits: string[];
  contentLocale: Locale;
};

export const CURATED_PACKAGES: Record<Locale, CuratedPackageCard[]> = {
  en: [
    {
      id: 'pkg-serengeti-migration-7d',
      slug: '7-day-great-migration-safari',
      title: '7-Day Great Migration & Ngorongoro Big Five Safari',
      summary: 'Follow the world-famous migration herds through Central and Northern Serengeti, descending into the wildlife-dense Ngorongoro Crater.',
      durationDays: 7,
      durationNights: 6,
      priceFrom: 2450,
      currency: 'USD',
      priceUnit: 'per person',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
      business: { slug: 'asilia-africa-tanzania', name: 'Asilia Africa', isVerified: true },
      visits: ['Serengeti National Park', 'Ngorongoro Crater', 'Lake Manyara'],
      contentLocale: 'en',
    },
    {
      id: 'pkg-kilimanjaro-lemosho-8d',
      slug: '8-day-kilimanjaro-lemosho-trek',
      title: '8-Day Mount Kilimanjaro Lemosho Route Expedition',
      summary: 'The scenic, high-acclimatization western approach across the Shira Plateau and Lava Tower to the 5,895m summit of Uhuru Peak.',
      durationDays: 8,
      durationNights: 7,
      priceFrom: 2190,
      currency: 'USD',
      priceUnit: 'per person',
      coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
      business: { slug: 'kibo-guides-tanzania', name: 'Kibo Guides', isVerified: true },
      visits: ['Mount Kilimanjaro'],
      contentLocale: 'en',
    },
    {
      id: 'pkg-tarangire-serengeti-5d',
      slug: '5-day-tarangire-serengeti-highlights',
      title: '5-Day Tarangire Elephants & Central Serengeti Predators',
      summary: 'Explore massive baobabs and elephant herds along Tarangire River before heading to Seronera Valley for prime big cat encounters.',
      durationDays: 5,
      durationNights: 4,
      priceFrom: 1750,
      currency: 'USD',
      priceUnit: 'per person',
      coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
      isFeatured: false,
      isDemo: false,
      business: { slug: 'nomad-tanzania', name: 'Nomad Tanzania', isVerified: true },
      visits: ['Tarangire National Park', 'Serengeti National Park'],
      contentLocale: 'en',
    },
    {
      id: 'pkg-bush-to-beach-6d',
      slug: '6-day-serengeti-zanzibar-bush-to-beach',
      title: '6-Day Bush to Beach: Serengeti Wildlife & Zanzibar Spice Coast',
      summary: 'Fly seamlessly from private safari game drives in the Serengeti to the turquoise waters, spice tours, and dhow cruises of Zanzibar.',
      durationDays: 6,
      durationNights: 5,
      priceFrom: 2850,
      currency: 'USD',
      priceUnit: 'per person',
      coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
      business: { slug: 'zanzibar-quest-safaris', name: 'Zanzibar Quest Safaris', isVerified: true },
      visits: ['Serengeti National Park', 'Zanzibar', 'Stone Town'],
      contentLocale: 'en',
    },
  ],
  de: [
    {
      id: 'pkg-serengeti-migration-7d',
      slug: '7-tage-grosse-migration-safari',
      title: '7 Tage Große Migration & Ngorongoro Krater Safari',
      summary: 'Erleben Sie die weltberühmte Gnu-Wanderung in der Serengeti und steigen Sie in den tierreichen Ngorongoro-Krater hinab.',
      durationDays: 7,
      durationNights: 6,
      priceFrom: 2450,
      currency: 'USD',
      priceUnit: 'pro Person',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
      business: { slug: 'asilia-africa-tanzania', name: 'Asilia Africa', isVerified: true },
      visits: ['Serengeti Nationalpark', 'Ngorongoro Krater', 'Lake Manyara'],
      contentLocale: 'de',
    },
  ],
  fr: [
    {
      id: 'pkg-serengeti-migration-7d',
      slug: 'safari-7-jours-grande-migration',
      title: 'Safari 7 Jours Grande Migration & Cratère du Ngorongoro',
      summary: 'Suivez la grande migration des gnous à travers le Serengeti et découvrez les Big Five au cœur du cratère du Ngorongoro.',
      durationDays: 7,
      durationNights: 6,
      priceFrom: 2450,
      currency: 'USD',
      priceUnit: 'par personne',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
      business: { slug: 'asilia-africa-tanzania', name: 'Asilia Africa', isVerified: true },
      visits: ['Parc National du Serengeti', 'Cratère du Ngorongoro', 'Lac Manyara'],
      contentLocale: 'fr',
    },
  ],
  it: [
    {
      id: 'pkg-serengeti-migration-7d',
      slug: 'safari-7-giorni-grande-migrazione',
      title: 'Safari 7 Giorni Grande Migrazione & Cratere di Ngorongoro',
      summary: 'Segui le mandrie della Grande Migrazione nel Serengeti e scendi nello spettacolare Cratere di Ngorongoro per avvistare i Big Five.',
      durationDays: 7,
      durationNights: 6,
      priceFrom: 2450,
      currency: 'USD',
      priceUnit: 'a persona',
      coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
      isFeatured: true,
      isDemo: false,
      business: { slug: 'asilia-africa-tanzania', name: 'Asilia Africa', isVerified: true },
      visits: ['Parco Nazionale del Serengeti', 'Cratere di Ngorongoro', 'Lago Manyara'],
      contentLocale: 'it',
    },
  ],
};

export const CURATED_EVENTS: Record<Locale, EventCard[]> = {
  en: [
    {
      id: 'event-sauti-za-busara',
      key: 'sauti_za_busara',
      kind: 'festival',
      name: 'Sauti za Busara',
      slug: 'sauti-za-busara',
      summary: 'East Africa’s premier African music festival held inside the historic Old Fort of Stone Town.',
      advice: 'Book flights and Stone Town heritage hotels 3-4 months in advance as rooms fill rapidly.',
      typicalMonth: 2,
      nextStart: '2027-02-12',
      nextEnd: '2027-02-15',
      countryCode: 'TZ',
      website: 'https://www.busaramusic.org',
      destination: { name: 'Stone Town', slug: 'stone-town' },
    },
    {
      id: 'event-kili-marathon',
      key: 'kilimanjaro_marathon',
      kind: 'sports',
      name: 'Kilimanjaro Marathon',
      slug: 'kilimanjaro-marathon',
      summary: 'Iconic marathon, half-marathon, and 5km fun run at the foot of Mount Kilimanjaro in Moshi.',
      advice: 'Combine with a post-race safari or Kibo summit expedition.',
      typicalMonth: 3,
      nextStart: '2027-03-01',
      nextEnd: '2027-03-01',
      countryCode: 'TZ',
      website: 'https://www.kilimanjaromarathon.com',
      destination: { name: 'Mount Kilimanjaro', slug: 'mount-kilimanjaro' },
    },
    {
      id: 'event-serengeti-calving',
      key: 'serengeti_calving',
      kind: 'wildlife',
      name: 'Serengeti Calving Gathering',
      slug: 'serengeti-calving-season',
      summary: 'Peak synchronized wildebeest births across the southern Ndutu plains with dramatic predator action.',
      advice: 'Stay in mobile tented camps near Ndutu for direct access to early morning hunts.',
      typicalMonth: 2,
      nextStart: null,
      nextEnd: null,
      countryCode: 'TZ',
      website: null,
      destination: { name: 'Serengeti National Park', slug: 'serengeti-national-park' },
    },
    {
      id: 'event-ziff',
      key: 'ziff_film_festival',
      kind: 'festival',
      name: 'Zanzibar International Film Festival (ZIFF)',
      slug: 'zanzibar-international-film-festival',
      summary: 'Celebration of African, Indian Ocean, and global cinema, music, and Dhow culture.',
      advice: 'Screenings are held in Stone Town’s open-air amphitheaters under starlit skies.',
      typicalMonth: 7,
      nextStart: '2027-07-08',
      nextEnd: '2027-07-16',
      countryCode: 'TZ',
      website: 'https://ziff.or.tz',
      destination: { name: 'Zanzibar', slug: 'zanzibar' },
    },
  ],
  de: [
    {
      id: 'event-sauti-za-busara',
      key: 'sauti_za_busara',
      kind: 'festival',
      name: 'Sauti za Busara',
      slug: 'sauti-za-busara',
      summary: 'Ostafrikas renommiertes afrikanisches Musikfestival im historischen Alten Fort von Stone Town.',
      advice: 'Flüge und Hotels in Stone Town 3-4 Monate im Voraus buchen.',
      typicalMonth: 2,
      nextStart: '2027-02-12',
      nextEnd: '2027-02-15',
      countryCode: 'TZ',
      website: 'https://www.busaramusic.org',
      destination: { name: 'Stone Town', slug: 'stone-town' },
    },
    {
      id: 'event-kili-marathon',
      key: 'kilimanjaro_marathon',
      kind: 'sports',
      name: 'Kilimanjaro Marathon',
      slug: 'kilimanjaro-marathon',
      summary: 'Legendärer Marathon am Fuße des höchsten Berges Afrikas in Moshi.',
      advice: 'Ideal kombinierbar mit einer anschließenden Safari oder Bergbesteigung.',
      typicalMonth: 3,
      nextStart: '2027-03-01',
      nextEnd: '2027-03-01',
      countryCode: 'TZ',
      website: 'https://www.kilimanjaromarathon.com',
      destination: { name: 'Mount Kilimanjaro', slug: 'mount-kilimanjaro' },
    },
    {
      id: 'event-serengeti-calving',
      key: 'serengeti_calving',
      kind: 'wildlife',
      name: 'Serengeti Kalbezeit',
      slug: 'serengeti-kalbezeit',
      summary: 'Synchronisierte Geburten der Gnus in den Ndutu-Ebenen mit spektakulären Raubtierszenen.',
      advice: 'Mobile Zeltcamps in der Nähe von Ndutu buchen für frühmorgendliche Beobachtungen.',
      typicalMonth: 2,
      nextStart: null,
      nextEnd: null,
      countryCode: 'TZ',
      website: null,
      destination: { name: 'Serengeti National Park', slug: 'serengeti-national-park' },
    },
    {
      id: 'event-ziff',
      key: 'ziff_film_festival',
      kind: 'festival',
      name: 'Zanzibar International Film Festival (ZIFF)',
      slug: 'zanzibar-film-festival',
      summary: 'Fest des afrikanischen Kinos, der Dhow-Kultur und Musik in Stone Town.',
      advice: 'Freiluftvorführungen im Amphitheater des Alten Forts unter dem Sternenhimmel.',
      typicalMonth: 7,
      nextStart: '2027-07-08',
      nextEnd: '2027-07-16',
      countryCode: 'TZ',
      website: 'https://ziff.or.tz',
      destination: { name: 'Zanzibar', slug: 'zanzibar' },
    },
  ],
  fr: [
    {
      id: 'event-sauti-za-busara',
      key: 'sauti_za_busara',
      kind: 'festival',
      name: 'Sauti za Busara',
      slug: 'sauti-za-busara',
      summary: 'Le plus grand festival de musique africaine d’Afrique de l’Est dans le Vieux Fort de Stone Town.',
      advice: 'Réservez vos hébergements à Stone Town plusieurs mois à l’avance.',
      typicalMonth: 2,
      nextStart: '2027-02-12',
      nextEnd: '2027-02-15',
      countryCode: 'TZ',
      website: 'https://www.busaramusic.org',
      destination: { name: 'Stone Town', slug: 'stone-town' },
    },
    {
      id: 'event-kili-marathon',
      key: 'kilimanjaro_marathon',
      kind: 'sports',
      name: 'Marathon du Kilimandjaro',
      slug: 'marathon-kilimandjaro',
      summary: 'Course emblématique de 42 km et 21 km au pied du Kilimandjaro à Moshi.',
      advice: 'À combiner avec un safari ou l’ascension du Kibo.',
      typicalMonth: 3,
      nextStart: '2027-03-01',
      nextEnd: '2027-03-01',
      countryCode: 'TZ',
      website: 'https://www.kilimanjaromarathon.com',
      destination: { name: 'Mount Kilimanjaro', slug: 'mount-kilimanjaro' },
    },
    {
      id: 'event-serengeti-calving',
      key: 'serengeti_calving',
      kind: 'wildlife',
      name: 'Saison des Naissances du Serengeti',
      slug: 'saison-naissances-serengeti',
      summary: 'Naissances massives des gnous dans les plaines de Ndutu avec forte présence de prédateurs.',
      advice: 'Privilégiez les camps de tentes mobiles près de Ndutu.',
      typicalMonth: 2,
      nextStart: null,
      nextEnd: null,
      countryCode: 'TZ',
      website: null,
      destination: { name: 'Serengeti National Park', slug: 'serengeti-national-park' },
    },
    {
      id: 'event-ziff',
      key: 'ziff_film_festival',
      kind: 'festival',
      name: 'Festival International du Film de Zanzibar (ZIFF)',
      slug: 'festival-film-zanzibar',
      summary: 'Célébration du cinéma africain et de la culture des dhows à Zanzibar.',
      advice: 'Projections en plein air au cœur de Stone Town.',
      typicalMonth: 7,
      nextStart: '2027-07-08',
      nextEnd: '2027-07-16',
      countryCode: 'TZ',
      website: 'https://ziff.or.tz',
      destination: { name: 'Zanzibar', slug: 'zanzibar' },
    },
  ],
  it: [
    {
      id: 'event-sauti-za-busara',
      key: 'sauti_za_busara',
      kind: 'festival',
      name: 'Sauti za Busara',
      slug: 'sauti-za-busara',
      summary: 'Il più importante festival di musica africana dell’Africa orientale nel Forte Vecchio di Stone Town.',
      advice: 'Prenotare alloggio e voli con largo anticipo per la grande affluenza.',
      typicalMonth: 2,
      nextStart: '2027-02-12',
      nextEnd: '2027-02-15',
      countryCode: 'TZ',
      website: 'https://www.busaramusic.org',
      destination: { name: 'Stone Town', slug: 'stone-town' },
    },
    {
      id: 'event-kili-marathon',
      key: 'kilimanjaro_marathon',
      kind: 'sports',
      name: 'Maratona del Kilimangiaro',
      slug: 'maratona-kilimangiaro',
      summary: 'Corsa leggendaria ai piedi del tetto d’Africa a Moshi.',
      advice: 'Ideale da abbinare a un safari nei parchi del Nord o all’ascesa in vetta.',
      typicalMonth: 3,
      nextStart: '2027-03-01',
      nextEnd: '2027-03-01',
      countryCode: 'TZ',
      website: 'https://www.kilimanjaromarathon.com',
      destination: { name: 'Mount Kilimanjaro', slug: 'mount-kilimanjaro' },
    },
    {
      id: 'event-serengeti-calving',
      key: 'serengeti_calving',
      kind: 'wildlife',
      name: 'Stagione dei Parti nel Serengeti',
      slug: 'stagione-parti-serengeti',
      summary: 'Migliaia di cuccioli di gnu nascono nelle pianure di Ndutu richiamando i grandi felini.',
      advice: 'Soggiornare nei campi tendati mobili a Ndutu per le migliori uscite all’alba.',
      typicalMonth: 2,
      nextStart: null,
      nextEnd: null,
      countryCode: 'TZ',
      website: null,
      destination: { name: 'Serengeti National Park', slug: 'serengeti-national-park' },
    },
    {
      id: 'event-ziff',
      key: 'ziff_film_festival',
      kind: 'festival',
      name: 'Festival Internazionale del Cinema di Zanzibar (ZIFF)',
      slug: 'festival-cinema-zanzibar',
      summary: 'Il grande festival del cinema africano e della cultura dhow a Stone Town.',
      advice: 'Proiezioni all’aperto sotto il cielo stellato di Stone Town.',
      typicalMonth: 7,
      nextStart: '2027-07-08',
      nextEnd: '2027-07-16',
      countryCode: 'TZ',
      website: 'https://ziff.or.tz',
      destination: { name: 'Zanzibar', slug: 'zanzibar' },
    },
  ],
};
