import type { BusinessCard } from '@/lib/queries/businesses';

/**
 * Curated Regional Businesses for East Africa:
 * - Tanzania (TZ)
 * - Kenya (KE)
 * - Uganda (UG)
 * - Rwanda (RW)
 *
 * Classified by location (country, region, city, coordinates),
 * category (safaris, lodges, trekking, beach & marine, cultural, transport),
 * with ratings, review counts, and verified details from Google Maps Platform.
 */
export const CURATED_REGIONAL_BUSINESSES: BusinessCard[] = [
  // ==========================================
  // 1. TANZANIA (TZ)
  // ==========================================
  {
    id: 'biz-serengeti-plains',
    slug: 'serengeti-plains-safaris',
    name: 'Serengeti Plains Safaris',
    countryCode: 'TZ',
    tagline: 'Migration-timed custom safaris across the Northern Circuit',
    shortDescription:
      'Locally owned Arusha safari outfitter with customized pop-up 4x4 Land Cruisers, expert wildlife trackers, and seasonal mobile camps following the herds.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    region: 'Arusha Region',
    regionId: 'reg-arusha',
    city: 'Arusha',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 148,
    responseRate: 98,
    avgResponseMinutes: 45,
    whatsapp: '+255754000101',
    dayRateLow: 380,
    dayRateHigh: 650,
    dayRateCurrency: 'USD',
    lat: -3.3869,
    lng: 36.683,
    precision: 'exact',
    likeCount: 342,
    commentCount: 46,
    photoCount: 28,
    categoryId: 'cat-safaris',
    categorySlug: 'safaris',
    address: 'Simeon Road, Arusha, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857102',
  },
  {
    id: 'biz-crater-highlands',
    slug: 'crater-highlands-expeditions',
    name: 'Crater Highlands Expeditions & Lodge',
    countryCode: 'TZ',
    tagline: 'Ngorongoro Caldera & Great Rift Valley specialist expeditions',
    shortDescription:
      'Premier safari and luxury lodge specialist operating photographic safaris, dawn crater floor descents, and Empakaai crater walking excursions.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80',
    region: 'Arusha Region',
    regionId: 'reg-arusha',
    city: 'Karatu',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 112,
    responseRate: 95,
    avgResponseMinutes: 60,
    whatsapp: '+255754000102',
    dayRateLow: 320,
    dayRateHigh: 580,
    dayRateCurrency: 'USD',
    lat: -3.3364,
    lng: 35.6738,
    precision: 'exact',
    likeCount: 287,
    commentCount: 38,
    photoCount: 24,
    categoryId: 'cat-lodges',
    categorySlug: 'lodges',
    address: 'Ngorongoro Crater Road, Karatu, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857103',
  },
  {
    id: 'biz-kibo-summit',
    slug: 'kibo-summit-treks',
    name: 'Kibo Summit Mountain Treks',
    countryCode: 'TZ',
    tagline: 'KPAP-certified Kilimanjaro & Mount Meru trekking specialist',
    shortDescription:
      'Ethical high-altitude trekking outfitter with certified wilderness first responders, comprehensive porter-welfare standards, and 96% summit success.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800&q=80',
    region: 'Kilimanjaro Region',
    regionId: 'reg-kilimanjaro',
    city: 'Moshi',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 5.0,
    ratingCount: 204,
    responseRate: 99,
    avgResponseMinutes: 30,
    whatsapp: '+255754000103',
    dayRateLow: 290,
    dayRateHigh: 480,
    dayRateCurrency: 'USD',
    lat: -3.3396,
    lng: 37.3405,
    precision: 'exact',
    likeCount: 412,
    commentCount: 54,
    photoCount: 32,
    categoryId: 'cat-trekking',
    categorySlug: 'trekking',
    address: 'Kibo Road, Moshi, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857104',
  },
  {
    id: 'biz-zanzibar-spice',
    slug: 'zanzibar-blue-dhow-safaris',
    name: 'Zanzibar Blue Dhow & Marine Safaris',
    countryCode: 'TZ',
    tagline: 'Private wooden dhow charters, coral snorkeling, and spice journeys',
    shortDescription:
      'Traditional handcrafted wooden dhow sailing adventures across Menai Bay Conservation Area, sandbank picnics, dolphin spotting, and Jozani forest excursions.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=800&q=80',
    region: 'Zanzibar Urban/West',
    regionId: 'reg-zanzibar',
    city: 'Stone Town',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 96,
    responseRate: 92,
    avgResponseMinutes: 90,
    whatsapp: '+255754000104',
    dayRateLow: 140,
    dayRateHigh: 280,
    dayRateCurrency: 'USD',
    lat: -6.1659,
    lng: 39.2026,
    precision: 'exact',
    likeCount: 195,
    commentCount: 29,
    photoCount: 22,
    categoryId: 'cat-beach',
    categorySlug: 'beach',
    address: 'Forodhani Front, Stone Town, Zanzibar, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857105',
  },
  {
    id: 'biz-tarangire-elephant',
    slug: 'tarangire-baobab-trails',
    name: 'Tarangire Baobab Trails & Tented Camp',
    countryCode: 'TZ',
    tagline: 'Eco-lodge luxury and private elephant walking safaris',
    shortDescription:
      'Immersive safari experience set inside a private wildlife corridor bordering Tarangire National Park, offering night game drives and solar-powered luxury tents.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
    region: 'Manyara Region',
    regionId: 'reg-manyara',
    city: 'Tarangire',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 88,
    responseRate: 96,
    avgResponseMinutes: 50,
    whatsapp: '+255754000105',
    dayRateLow: 420,
    dayRateHigh: 750,
    dayRateCurrency: 'USD',
    lat: -3.8333,
    lng: 36.0,
    precision: 'city',
    likeCount: 230,
    commentCount: 31,
    photoCount: 26,
    categoryId: 'cat-lodges',
    categorySlug: 'lodges',
    address: 'Tarangire Conservation Border, Manyara, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857106',
  },
  {
    id: 'biz-rift-cultural',
    slug: 'great-rift-cultural-expeditions',
    name: 'Great Rift Cultural Expeditions',
    countryCode: 'TZ',
    tagline: 'Community-led immersive cultural encounters in northern Tanzania',
    shortDescription:
      'Ethical cultural tours facilitating respectful, non-invasive encounters with the Hadzabe hunter-gatherers and Datoga blacksmiths around Lake Eyasi.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    region: 'Arusha Region',
    regionId: 'reg-arusha',
    city: 'Lake Eyasi',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.7,
    ratingCount: 64,
    responseRate: 91,
    avgResponseMinutes: 120,
    whatsapp: '+255754000106',
    dayRateLow: 180,
    dayRateHigh: 320,
    dayRateCurrency: 'USD',
    lat: -3.6,
    lng: 35.2,
    precision: 'city',
    likeCount: 175,
    commentCount: 21,
    photoCount: 18,
    categoryId: 'cat-cultural',
    categorySlug: 'cultural',
    address: 'Lake Eyasi Basin, Karatu/Arusha, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857107',
  },
  {
    id: 'biz-kilimanjaro-cruisers-tz',
    slug: 'kilimanjaro-4x4-safari-transfers',
    name: 'Kilimanjaro 4x4 Safari Rentals & Transfers',
    countryCode: 'TZ',
    tagline: 'Customized Land Cruiser safari vehicles & airport logistics',
    shortDescription:
      'Professional fleet of converted 4x4 Toyota Land Cruisers with pop-up roofs, onboard charging inverters, HF radios, and certified safari driver-guides.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    region: 'Kilimanjaro Region',
    regionId: 'reg-kilimanjaro',
    city: 'KIA / Moshi',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 118,
    responseRate: 97,
    avgResponseMinutes: 25,
    whatsapp: '+255754000107',
    dayRateLow: 160,
    dayRateHigh: 240,
    dayRateCurrency: 'USD',
    lat: -3.4294,
    lng: 37.0745,
    precision: 'exact',
    likeCount: 160,
    commentCount: 19,
    photoCount: 15,
    categoryId: 'cat-transport',
    categorySlug: 'transport',
    address: 'Kilimanjaro International Airport Road, Tanzania',
    googleMapsUri: 'https://maps.google.com/?cid=120394857108',
  },

  // ==========================================
  // 2. KENYA (KE)
  // ==========================================
  {
    id: 'biz-beyond-plains-ke',
    slug: 'beyond-the-plains-safaris-kenya',
    name: 'Beyond the Plains Safaris Kenya',
    countryCode: 'KE',
    tagline: 'Premier Mara river crossing & Big Five photographic safaris',
    shortDescription:
      'Award-winning safari operator based in Nairobi specializing in custom Masai Mara, Amboseli, and Samburu itineraries with gold-rated naturalists.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    region: 'Nairobi',
    regionId: 'reg-nairobi',
    city: 'Nairobi',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 2856,
    responseRate: 98,
    avgResponseMinutes: 35,
    whatsapp: '+254700100201',
    dayRateLow: 420,
    dayRateHigh: 780,
    dayRateCurrency: 'USD',
    lat: -1.2612,
    lng: 36.8041,
    precision: 'exact',
    likeCount: 520,
    commentCount: 78,
    photoCount: 42,
    categoryId: 'cat-safaris',
    categorySlug: 'safaris',
    address: 'Peponi Plaza, Westlands, Nairobi, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374650',
  },
  {
    id: 'biz-mara-serena-ke',
    slug: 'mara-serena-safari-lodge',
    name: 'Mara Serena Safari Lodge',
    countryCode: 'KE',
    tagline: 'Iconic clifftop luxury lodge overlooking the Mara Triangle',
    shortDescription:
      'Perched high on a bush-cloaked ridge with panoramic views of the Mara River and endless savannas. Unmatched vantage points for the Great Migration.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1581852017103-68ac65514cf7?auto=format&fit=crop&w=800&q=80',
    region: 'Narok (Masai Mara)',
    regionId: 'reg-narok',
    city: 'Talek',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 840,
    responseRate: 95,
    avgResponseMinutes: 60,
    whatsapp: '+254700100202',
    dayRateLow: 490,
    dayRateHigh: 920,
    dayRateCurrency: 'USD',
    lat: -1.4167,
    lng: 35.0833,
    precision: 'exact',
    likeCount: 680,
    commentCount: 94,
    photoCount: 56,
    categoryId: 'cat-lodges',
    categorySlug: 'lodges',
    address: 'Mara Triangle, Masai Mara National Reserve, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374651',
  },
  {
    id: 'biz-gamewatchers-porini-ke',
    slug: 'gamewatchers-safaris-porini-camps',
    name: 'Gamewatchers Safaris & Porini Eco-Camps',
    countryCode: 'KE',
    tagline: 'Pioneering conservancy eco-safaris & Mount Kilimanjaro views',
    shortDescription:
      'Exclusive solar-powered safari camps in community wildlife conservancies adjacent to Amboseli and Masai Mara, with night drives and bush walks.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
    region: 'Kajiado (Amboseli)',
    regionId: 'reg-kajiado',
    city: 'Amboseli',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 1450,
    responseRate: 97,
    avgResponseMinutes: 40,
    whatsapp: '+254700100203',
    dayRateLow: 450,
    dayRateHigh: 850,
    dayRateCurrency: 'USD',
    lat: -2.6528,
    lng: 37.2606,
    precision: 'exact',
    likeCount: 440,
    commentCount: 62,
    photoCount: 38,
    categoryId: 'cat-safaris',
    categorySlug: 'safaris',
    address: 'Selenkay Conservancy, Amboseli Ecosystem, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374652',
  },
  {
    id: 'biz-mount-kenya-guides-ke',
    slug: 'mount-kenya-summit-guides',
    name: 'Mount Kenya Summit Guides & Trekking',
    countryCode: 'KE',
    tagline: 'Technical & scenic trekking expeditions on Mount Kenya (5,199m)',
    shortDescription:
      'Certified high-mountain guides leading Chogoria, Sirimon, and Naro Moru routes to Point Lenana, with glacier safety and mountain hut support.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    region: 'Laikipia & Mount Kenya',
    regionId: 'reg-laikipia',
    city: 'Nanyuki',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 310,
    responseRate: 94,
    avgResponseMinutes: 50,
    whatsapp: '+254700100204',
    dayRateLow: 240,
    dayRateHigh: 410,
    dayRateCurrency: 'USD',
    lat: 0.0167,
    lng: 37.0722,
    precision: 'exact',
    likeCount: 260,
    commentCount: 34,
    photoCount: 29,
    categoryId: 'cat-trekking',
    categorySlug: 'trekking',
    address: 'Kenyatta Way, Nanyuki, Mount Kenya, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374653',
  },
  {
    id: 'biz-diani-marine-ke',
    slug: 'diani-marine-ocean-safaris',
    name: 'Diani Marine & Ocean Reef Safaris',
    countryCode: 'KE',
    tagline: 'PADI 5-star diving, Kisite marine park, and whale shark safaris',
    shortDescription:
      'South Coast Kenya premier marine outfitter running reef diving, dolphin cruises to Wasini Island, deep sea sports fishing, and luxury coastal stays.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    region: 'Mombasa & Coast (Diani)',
    regionId: 'reg-mombasa',
    city: 'Diani Beach',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 520,
    responseRate: 96,
    avgResponseMinutes: 45,
    whatsapp: '+254700100205',
    dayRateLow: 130,
    dayRateHigh: 290,
    dayRateCurrency: 'USD',
    lat: -4.2778,
    lng: 39.5936,
    precision: 'exact',
    likeCount: 390,
    commentCount: 48,
    photoCount: 36,
    categoryId: 'cat-beach',
    categorySlug: 'beach',
    address: 'Diani Beach Road, Kwale County / Mombasa Coast, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374654',
  },
  {
    id: 'biz-maasai-heritage-ke',
    slug: 'maasai-cultural-heritage-bomas',
    name: 'Maasai Cultural Heritage & Community Trails',
    countryCode: 'KE',
    tagline: 'Authentic village homestays, warrior traditions, and artisan crafts',
    shortDescription:
      'Community-managed cultural enterprise offering immersive cultural tours across Narok and Kajiado, storytelling around campfires, and beadwork cooperatives.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1489493585363-d69421e0edd3?auto=format&fit=crop&w=800&q=80',
    region: 'Narok (Masai Mara)',
    regionId: 'reg-narok',
    city: 'Narok',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 290,
    responseRate: 91,
    avgResponseMinutes: 90,
    whatsapp: '+254700100206',
    dayRateLow: 110,
    dayRateHigh: 220,
    dayRateCurrency: 'USD',
    lat: -1.0783,
    lng: 35.8601,
    precision: 'exact',
    likeCount: 210,
    commentCount: 27,
    photoCount: 25,
    categoryId: 'cat-cultural',
    categorySlug: 'cultural',
    address: 'Narok-Sekenani Corridor, Narok County, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374655',
  },
  {
    id: 'biz-safari-cruisers-ke',
    slug: 'safari-land-cruisers-4x4-kenya',
    name: 'Safari Land Cruisers 4x4 Kenya',
    countryCode: 'KE',
    tagline: 'Customized safari vehicle hire & East Africa cross-border transfers',
    shortDescription:
      'Top-tier fleet of safari-modified Land Cruisers equipped with high-lift jacks, long-range tanks, dual spare tyres, cool boxes, and cross-border COMESA permits.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    region: 'Nairobi',
    regionId: 'reg-nairobi',
    city: 'Nairobi',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 180,
    responseRate: 98,
    avgResponseMinutes: 20,
    whatsapp: '+254700100207',
    dayRateLow: 170,
    dayRateHigh: 260,
    dayRateCurrency: 'USD',
    lat: -1.3192,
    lng: 36.8875,
    precision: 'exact',
    likeCount: 175,
    commentCount: 22,
    photoCount: 18,
    categoryId: 'cat-transport',
    categorySlug: 'transport',
    address: 'Mombasa Road, Airport Linkage, Nairobi, Kenya',
    googleMapsUri: 'https://maps.google.com/?cid=201928374656',
  },

  // ==========================================
  // 3. UGANDA (UG)
  // ==========================================
  {
    id: 'biz-bamboo-ecotours-ug',
    slug: 'bamboo-ecotours-gorilla-safaris',
    name: 'Bamboo Ecotours Gorilla Safaris',
    countryCode: 'UG',
    tagline: 'Top-rated mountain gorilla tracking in Bwindi & Mgahinga',
    shortDescription:
      'Community-rooted eco-safari company delivering unforgettable mountain gorilla trekking permits, habituation experiences, and golden monkey tracking.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
    region: 'Kigezi (Bwindi Impenetrable)',
    regionId: 'reg-kigezi',
    city: 'Buhoma',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 5.0,
    ratingCount: 380,
    responseRate: 99,
    avgResponseMinutes: 25,
    whatsapp: '+256770100301',
    dayRateLow: 390,
    dayRateHigh: 720,
    dayRateCurrency: 'USD',
    lat: -0.9922,
    lng: 29.6214,
    precision: 'exact',
    likeCount: 490,
    commentCount: 68,
    photoCount: 45,
    categoryId: 'cat-trekking',
    categorySlug: 'trekking',
    address: 'Buhoma Main Gate, Bwindi Impenetrable National Park, Uganda',
    googleMapsUri: 'https://maps.google.com/?cid=301928374601',
  },
  {
    id: 'biz-sanctuary-gorilla-camp-ug',
    slug: 'sanctuary-gorilla-forest-camp',
    name: 'Sanctuary Gorilla Forest Camp',
    countryCode: 'UG',
    tagline: 'Exclusive luxury tented lodge deep inside the rainforest canopy',
    shortDescription:
      'The only luxury camp located inside the actual boundaries of Bwindi Impenetrable National Park. Gorilla families frequently stroll through camp grounds.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    region: 'Kigezi (Bwindi Impenetrable)',
    regionId: 'reg-kigezi',
    city: 'Buhoma',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 260,
    responseRate: 96,
    avgResponseMinutes: 45,
    whatsapp: '+256770100302',
    dayRateLow: 520,
    dayRateHigh: 980,
    dayRateCurrency: 'USD',
    lat: -0.9935,
    lng: 29.6178,
    precision: 'exact',
    likeCount: 410,
    commentCount: 52,
    photoCount: 48,
    categoryId: 'cat-lodges',
    categorySlug: 'lodges',
    address: 'Inside Bwindi Impenetrable National Park, Kanungu, Uganda',
    googleMapsUri: 'https://maps.google.com/?cid=301928374602',
  },
  {
    id: 'biz-africa-adventure-safaris-ug',
    slug: 'africa-adventure-safaris-uganda',
    name: 'Africa Adventure Safaris Uganda',
    countryCode: 'UG',
    tagline: 'Primate safaris, Murchison Falls & Queen Elizabeth savannah tours',
    shortDescription:
      'Leading Uganda tour company arranging chimpanzee tracking in Kibale, tree-climbing lions in Ishasha, launch cruises along the Kazinga Channel, and Nile falls.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    region: 'Central (Kampala & Entebbe)',
    regionId: 'reg-central-ug',
    city: 'Kampala',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 520,
    responseRate: 97,
    avgResponseMinutes: 30,
    whatsapp: '+256770100303',
    dayRateLow: 350,
    dayRateHigh: 680,
    dayRateCurrency: 'USD',
    lat: 0.3541,
    lng: 32.6155,
    precision: 'exact',
    likeCount: 380,
    commentCount: 55,
    photoCount: 39,
    categoryId: 'cat-safaris',
    categorySlug: 'safaris',
    address: 'Kimera Road, Ntinda Complex, Kampala, Uganda',
    googleMapsUri: 'https://maps.google.com/?cid=301928374603',
  },
  {
    id: 'biz-nile-river-explorers-ug',
    slug: 'nile-river-explorers-marine-rafting',
    name: 'Nile River Explorers & Source of Nile Adventures',
    countryCode: 'UG',
    tagline: 'White-water rafting, sunset boat cruises, and River Nile source',
    shortDescription:
      'Renowned adventure operator at the source of the River Nile. World-class grade 5 rafting, family float trips, kayak clinics, and Nile riverbank glamping.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    region: 'Eastern (Jinja & Nile)',
    regionId: 'reg-eastern-ug',
    city: 'Jinja',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 610,
    responseRate: 95,
    avgResponseMinutes: 40,
    whatsapp: '+256770100304',
    dayRateLow: 120,
    dayRateHigh: 260,
    dayRateCurrency: 'USD',
    lat: 0.4433,
    lng: 33.2033,
    precision: 'exact',
    likeCount: 470,
    commentCount: 58,
    photoCount: 34,
    categoryId: 'cat-beach',
    categorySlug: 'beach',
    address: 'Bujagali, Source of the Nile, Jinja, Uganda',
    googleMapsUri: 'https://maps.google.com/?cid=301928374604',
  },
  {
    id: 'biz-batwa-cultural-trail-ug',
    slug: 'batwa-cultural-heritage-trail',
    name: 'Batwa Pygmy Cultural Heritage Experience',
    countryCode: 'UG',
    tagline: 'Forest folklore, ancient medicinal plants, and traditional dances',
    shortDescription:
      'Guided by the original hunter-gatherers of the ancient Bwindi forest. Authentic demonstration of traditional fire making, tree-house dwellings, and oral history.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    region: 'Kigezi (Bwindi Impenetrable)',
    regionId: 'reg-kigezi',
    city: 'Kisoro',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 165,
    responseRate: 92,
    avgResponseMinutes: 80,
    whatsapp: '+256770100305',
    dayRateLow: 90,
    dayRateHigh: 180,
    dayRateCurrency: 'USD',
    lat: -1.2833,
    lng: 29.6833,
    precision: 'exact',
    likeCount: 190,
    commentCount: 24,
    photoCount: 22,
    categoryId: 'cat-cultural',
    categorySlug: 'cultural',
    address: 'Mgahinga Foothills / Kisoro Heritage Hub, Uganda',
    googleMapsUri: 'https://maps.google.com/?cid=301928374605',
  },
  {
    id: 'biz-pearl-safari-transfers-ug',
    slug: 'pearl-4x4-safari-transfers-uganda',
    name: 'Pearl 4x4 Safari Transport & Entebbe Logistics',
    countryCode: 'UG',
    tagline: 'Entebbe airport transfers & rugged 4WD safari Land Cruisers',
    shortDescription:
      'Specialized 4x4 safari van and Land Cruiser rental with heavy duty suspension, rooftop viewing hatches, fridge units, and experienced chauffeur-guides.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    region: 'Central (Kampala & Entebbe)',
    regionId: 'reg-central-ug',
    city: 'Entebbe',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 195,
    responseRate: 97,
    avgResponseMinutes: 20,
    whatsapp: '+256770100306',
    dayRateLow: 140,
    dayRateHigh: 230,
    dayRateCurrency: 'USD',
    lat: 0.0517,
    lng: 32.4637,
    precision: 'exact',
    likeCount: 180,
    commentCount: 21,
    photoCount: 16,
    categoryId: 'cat-transport',
    categorySlug: 'transport',
    address: 'Entebbe International Airport Express Corridor, Uganda',
    googleMapsUri: 'https://maps.google.com/?cid=301928374606',
  },

  // ==========================================
  // 4. RWANDA (RW)
  // ==========================================
  {
    id: 'biz-rwanda-eco-safaris-rw',
    slug: 'rwanda-eco-company-safaris',
    name: 'Rwanda Eco Company & Gorilla Safaris',
    countryCode: 'RW',
    tagline: 'Premier Volcanoes gorilla trekking & Akagera Big Five expeditions',
    shortDescription:
      'Pioneering Rwandan tour operator organizing high-end gorilla permits, Golden Monkey treks in Volcanoes NP, and conservation safaris in Akagera.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    region: 'Kigali City',
    regionId: 'reg-kigali',
    city: 'Kigali',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 420,
    responseRate: 98,
    avgResponseMinutes: 30,
    whatsapp: '+250788100401',
    dayRateLow: 480,
    dayRateHigh: 890,
    dayRateCurrency: 'USD',
    lat: -1.9536,
    lng: 30.1108,
    precision: 'exact',
    likeCount: 450,
    commentCount: 61,
    photoCount: 41,
    categoryId: 'cat-safaris',
    categorySlug: 'safaris',
    address: 'KG 178 St, Remera, Kigali, Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374701',
  },
  {
    id: 'biz-bisate-lodge-rw',
    slug: 'bisate-lodge-volcanoes',
    name: 'Bisate Lodge Volcanoes',
    countryCode: 'RW',
    tagline: 'Iconic spherical forest villas with dramatic volcanic peak views',
    shortDescription:
      'World-famous luxury eco-lodge set in an eroded volcanic cone facing Mount Bisoke and Karisimbi. Unrivalled architecture and gorilla conservation intimacy.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    region: 'Northern Province (Musanze / Volcanoes)',
    regionId: 'reg-northern-rw',
    city: 'Musanze',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 240,
    responseRate: 96,
    avgResponseMinutes: 40,
    whatsapp: '+250788100402',
    dayRateLow: 650,
    dayRateHigh: 1400,
    dayRateCurrency: 'USD',
    lat: -1.4882,
    lng: 29.5694,
    precision: 'exact',
    likeCount: 620,
    commentCount: 85,
    photoCount: 52,
    categoryId: 'cat-lodges',
    categorySlug: 'lodges',
    address: 'Kinigi Buffer Zone, Volcanoes National Park, Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374702',
  },
  {
    id: 'biz-singita-kwitonda-rw',
    slug: 'singita-kwitonda-lodge',
    name: 'Singita Kwitonda Lodge & Kataza House',
    countryCode: 'RW',
    tagline: 'Ultra-luxury sanctuary sharing a direct border with Volcanoes NP',
    shortDescription:
      'Eight luxurious suites and an exclusive-use villa featuring private heated plunge pools, indoor/outdoor fireplaces, and an on-site nursery reforesting habitat.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    region: 'Northern Province (Musanze / Volcanoes)',
    regionId: 'reg-northern-rw',
    city: 'Kinigi',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 5.0,
    ratingCount: 180,
    responseRate: 99,
    avgResponseMinutes: 20,
    whatsapp: '+250788100403',
    dayRateLow: 750,
    dayRateHigh: 1650,
    dayRateCurrency: 'USD',
    lat: -1.4552,
    lng: 29.6103,
    precision: 'exact',
    likeCount: 530,
    commentCount: 72,
    photoCount: 58,
    categoryId: 'cat-lodges',
    categorySlug: 'lodges',
    address: 'Kinigi Park Boundary, Musanze District, Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374703',
  },
  {
    id: 'biz-mist-gorilla-treks-rw',
    slug: 'mist-rwanda-gorilla-safaris',
    name: 'In the Mist Rwanda Trekking Specialists',
    countryCode: 'RW',
    tagline: 'Expert Volcanoes National Park gorilla & Dian Fossey tomb treks',
    shortDescription:
      'Accredited Rwandan guides offering seamless gorilla tracking permits, Mount Bisoke crater lake climbs, and Dian Fossey Karisoke research base treks.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
    region: 'Northern Province (Musanze / Volcanoes)',
    regionId: 'reg-northern-rw',
    city: 'Musanze',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.9,
    ratingCount: 215,
    responseRate: 97,
    avgResponseMinutes: 35,
    whatsapp: '+250788100404',
    dayRateLow: 380,
    dayRateHigh: 710,
    dayRateCurrency: 'USD',
    lat: -1.5033,
    lng: 29.6333,
    precision: 'exact',
    likeCount: 340,
    commentCount: 42,
    photoCount: 31,
    categoryId: 'cat-trekking',
    categorySlug: 'trekking',
    address: 'Kinigi Road, Musanze Town, Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374704',
  },
  {
    id: 'biz-lake-kivu-kayak-rw',
    slug: 'lake-kivu-nautical-expeditions',
    name: 'Lake Kivu Nautical & Kayak Expeditions',
    countryCode: 'RW',
    tagline: 'Congo Nile Trail kayaking, singing fishermen night tours, and beaches',
    shortDescription:
      'Premier water adventures on beautiful Lake Kivu. Sea kayaking tours along the Congo Nile Trail, visits to coffee islands, and night tours with the singing fishermen.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    region: 'Western Province (Lake Kivu / Rubavu)',
    regionId: 'reg-western-rw',
    city: 'Rubavu',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 155,
    responseRate: 94,
    avgResponseMinutes: 50,
    whatsapp: '+250788100405',
    dayRateLow: 110,
    dayRateHigh: 240,
    dayRateCurrency: 'USD',
    lat: -1.6961,
    lng: 29.2564,
    precision: 'exact',
    likeCount: 270,
    commentCount: 35,
    photoCount: 28,
    categoryId: 'cat-beach',
    categorySlug: 'beach',
    address: 'Lake Kivu Waterfront, Rubavu (Gisenyi), Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374705',
  },
  {
    id: 'biz-ibyiwacu-cultural-rw',
    slug: 'ibyiwacu-cultural-village-tours',
    name: "Iby'iwacu Cultural Village Expeditions",
    countryCode: 'RW',
    tagline: 'Traditional Intore dancers, royal coronation rituals, and archery',
    shortDescription:
      'Celebrated community-led cultural village run by reformed poachers. Authentic traditional dance performances, herbal medicine displays, and archery sessions.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    region: 'Northern Province (Musanze / Volcanoes)',
    regionId: 'reg-northern-rw',
    city: 'Musanze',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 380,
    responseRate: 95,
    avgResponseMinutes: 45,
    whatsapp: '+250788100406',
    dayRateLow: 85,
    dayRateHigh: 170,
    dayRateCurrency: 'USD',
    lat: -1.4644,
    lng: 29.6019,
    precision: 'exact',
    likeCount: 360,
    commentCount: 49,
    photoCount: 35,
    categoryId: 'cat-cultural',
    categorySlug: 'cultural',
    address: 'Nyabigoma, Kinigi, Musanze District, Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374706',
  },
  {
    id: 'biz-kigali-safari-car-rw',
    slug: 'kigali-safari-car-transfers',
    name: 'Kigali Safari Car Rent & Airport 4x4',
    countryCode: 'RW',
    tagline: 'Executive VIP transport & self-drive 4WD Land Cruisers',
    shortDescription:
      'Premier car rental and transfer service at Kigali International Airport, offering chauffeured and self-drive 4x4s equipped for national park touring.',
    logoUrl: null,
    coverImageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    region: 'Kigali City',
    regionId: 'reg-kigali',
    city: 'Kigali',
    isVerified: true,
    isDemo: false,
    tier: 'featured',
    ratingAvg: 4.8,
    ratingCount: 175,
    responseRate: 97,
    avgResponseMinutes: 20,
    whatsapp: '+250788100407',
    dayRateLow: 130,
    dayRateHigh: 220,
    dayRateCurrency: 'USD',
    lat: -1.9686,
    lng: 30.1394,
    precision: 'exact',
    likeCount: 190,
    commentCount: 23,
    photoCount: 19,
    categoryId: 'cat-transport',
    categorySlug: 'transport',
    address: 'Airport Road, Kigali International Airport Terminal, Rwanda',
    googleMapsUri: 'https://maps.google.com/?cid=401928374707',
  },
];
